// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewAsyncQueue creates a new instance of AsyncQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAsyncQueue[V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *AsyncQueue[V] {
	mock := &AsyncQueue[V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AsyncQueue is an autogenerated mock type for the AsyncQueue type
type AsyncQueue[V any] struct {
	mock.Mock
}

type AsyncQueue_Expecter[V any] struct {
	mock *mock.Mock
}

func (_m *AsyncQueue[V]) EXPECT() *AsyncQueue_Expecter[V] {
	return &AsyncQueue_Expecter[V]{mock: &_m.Mock}
}

// Len provides a mock function for the type AsyncQueue
func (_mock *AsyncQueue[V]) Len() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// AsyncQueue_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type AsyncQueue_Len_Call[V any] struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *AsyncQueue_Expecter[V]) Len() *AsyncQueue_Len_Call[V] {
	return &AsyncQueue_Len_Call[V]{Call: _e.mock.On("Len")}
}

func (_c *AsyncQueue_Len_Call[V]) Run(run func()) *AsyncQueue_Len_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AsyncQueue_Len_Call[V]) Return(n int) *AsyncQueue_Len_Call[V] {
	_c.Call.Return(n)
	return _c
}

func (_c *AsyncQueue_Len_Call[V]) RunAndReturn(run func() int) *AsyncQueue_Len_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Pop provides a mock function for the type AsyncQueue
func (_mock *AsyncQueue[V]) Pop(ctx context.Context, blocking bool, newDataSignalFlag chan bool) (V, error) {
	ret := _mock.Called(ctx, blocking, newDataSignalFlag)

	if len(ret) == 0 {
		panic("no return value specified for Pop")
	}

	var r0 V
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, chan bool) (V, error)); ok {
		return returnFunc(ctx, blocking, newDataSignalFlag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, chan bool) V); ok {
		r0 = returnFunc(ctx, blocking, newDataSignalFlag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, chan bool) error); ok {
		r1 = returnFunc(ctx, blocking, newDataSignalFlag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AsyncQueue_Pop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pop'
type AsyncQueue_Pop_Call[V any] struct {
	*mock.Call
}

// Pop is a helper method to define mock.On call
//   - ctx context.Context
//   - blocking bool
//   - newDataSignalFlag chan bool
func (_e *AsyncQueue_Expecter[V]) Pop(ctx interface{}, blocking interface{}, newDataSignalFlag interface{}) *AsyncQueue_Pop_Call[V] {
	return &AsyncQueue_Pop_Call[V]{Call: _e.mock.On("Pop", ctx, blocking, newDataSignalFlag)}
}

func (_c *AsyncQueue_Pop_Call[V]) Run(run func(ctx context.Context, blocking bool, newDataSignalFlag chan bool)) *AsyncQueue_Pop_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 chan bool
		if args[2] != nil {
			arg2 = args[2].(chan bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AsyncQueue_Pop_Call[V]) Return(v V, err error) *AsyncQueue_Pop_Call[V] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *AsyncQueue_Pop_Call[V]) RunAndReturn(run func(ctx context.Context, blocking bool, newDataSignalFlag chan bool) (V, error)) *AsyncQueue_Pop_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type AsyncQueue
func (_mock *AsyncQueue[V]) Push(ctx context.Context, data V) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, V) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AsyncQueue_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type AsyncQueue_Push_Call[V any] struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - data V
func (_e *AsyncQueue_Expecter[V]) Push(ctx interface{}, data interface{}) *AsyncQueue_Push_Call[V] {
	return &AsyncQueue_Push_Call[V]{Call: _e.mock.On("Push", ctx, data)}
}

func (_c *AsyncQueue_Push_Call[V]) Run(run func(ctx context.Context, data V)) *AsyncQueue_Push_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 V
		if args[1] != nil {
			arg1 = args[1].(V)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AsyncQueue_Push_Call[V]) Return(err error) *AsyncQueue_Push_Call[V] {
	_c.Call.Return(err)
	return _c
}

func (_c *AsyncQueue_Push_Call[V]) RunAndReturn(run func(ctx context.Context, data V) error) *AsyncQueue_Push_Call[V] {
	_c.Call.Return(run)
	return _c
}
