// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCondition creates a new instance of Condition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCondition(t interface {
	mock.TestingT
	Cleanup(func())
}) *Condition {
	mock := &Condition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Condition is an autogenerated mock type for the Condition type
type Condition struct {
	mock.Mock
}

type Condition_Expecter struct {
	mock *mock.Mock
}

func (_m *Condition) EXPECT() *Condition_Expecter {
	return &Condition_Expecter{mock: &_m.Mock}
}

// NotifyAll provides a mock function for the type Condition
func (_mock *Condition) NotifyAll() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NotifyAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Condition_NotifyAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyAll'
type Condition_NotifyAll_Call struct {
	*mock.Call
}

// NotifyAll is a helper method to define mock.On call
func (_e *Condition_Expecter) NotifyAll() *Condition_NotifyAll_Call {
	return &Condition_NotifyAll_Call{Call: _e.mock.On("NotifyAll")}
}

func (_c *Condition_NotifyAll_Call) Run(run func()) *Condition_NotifyAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Condition_NotifyAll_Call) Return(err error) *Condition_NotifyAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Condition_NotifyAll_Call) RunAndReturn(run func() error) *Condition_NotifyAll_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyOne provides a mock function for the type Condition
func (_mock *Condition) NotifyOne() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NotifyOne")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Condition_NotifyOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyOne'
type Condition_NotifyOne_Call struct {
	*mock.Call
}

// NotifyOne is a helper method to define mock.On call
func (_e *Condition_Expecter) NotifyOne() *Condition_NotifyOne_Call {
	return &Condition_NotifyOne_Call{Call: _e.mock.On("NotifyOne")}
}

func (_c *Condition_NotifyOne_Call) Run(run func()) *Condition_NotifyOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Condition_NotifyOne_Call) Return(err error) *Condition_NotifyOne_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Condition_NotifyOne_Call) RunAndReturn(run func() error) *Condition_NotifyOne_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type Condition
func (_mock *Condition) Wait(ctx context.Context, wakeUp chan bool) error {
	ret := _mock.Called(ctx, wakeUp)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chan bool) error); ok {
		r0 = returnFunc(ctx, wakeUp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Condition_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type Condition_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
//   - wakeUp chan bool
func (_e *Condition_Expecter) Wait(ctx interface{}, wakeUp interface{}) *Condition_Wait_Call {
	return &Condition_Wait_Call{Call: _e.mock.On("Wait", ctx, wakeUp)}
}

func (_c *Condition_Wait_Call) Run(run func(ctx context.Context, wakeUp chan bool)) *Condition_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chan bool
		if args[1] != nil {
			arg1 = args[1].(chan bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Condition_Wait_Call) Return(err error) *Condition_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Condition_Wait_Call) RunAndReturn(run func(ctx context.Context, wakeUp chan bool) error) *Condition_Wait_Call {
	_c.Call.Return(run)
	return _c
}
