// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewHTTPRequestMetricHelper creates a new instance of HTTPRequestMetricHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPRequestMetricHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPRequestMetricHelper {
	mock := &HTTPRequestMetricHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HTTPRequestMetricHelper is an autogenerated mock type for the HTTPRequestMetricHelper type
type HTTPRequestMetricHelper struct {
	mock.Mock
}

type HTTPRequestMetricHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *HTTPRequestMetricHelper) EXPECT() *HTTPRequestMetricHelper_Expecter {
	return &HTTPRequestMetricHelper_Expecter{mock: &_m.Mock}
}

// RecordRequest provides a mock function for the type HTTPRequestMetricHelper
func (_mock *HTTPRequestMetricHelper) RecordRequest(method string, status int, latency time.Duration, respSize int64) {
	_mock.Called(method, status, latency, respSize)
	return
}

// HTTPRequestMetricHelper_RecordRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordRequest'
type HTTPRequestMetricHelper_RecordRequest_Call struct {
	*mock.Call
}

// RecordRequest is a helper method to define mock.On call
//   - method string
//   - status int
//   - latency time.Duration
//   - respSize int64
func (_e *HTTPRequestMetricHelper_Expecter) RecordRequest(method interface{}, status interface{}, latency interface{}, respSize interface{}) *HTTPRequestMetricHelper_RecordRequest_Call {
	return &HTTPRequestMetricHelper_RecordRequest_Call{Call: _e.mock.On("RecordRequest", method, status, latency, respSize)}
}

func (_c *HTTPRequestMetricHelper_RecordRequest_Call) Run(run func(method string, status int, latency time.Duration, respSize int64)) *HTTPRequestMetricHelper_RecordRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *HTTPRequestMetricHelper_RecordRequest_Call) Return() *HTTPRequestMetricHelper_RecordRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *HTTPRequestMetricHelper_RecordRequest_Call) RunAndReturn(run func(method string, status int, latency time.Duration, respSize int64)) *HTTPRequestMetricHelper_RecordRequest_Call {
	_c.Run(run)
	return _c
}
