// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"time"

	"github.com/alwitt/goutils"
	mock "github.com/stretchr/testify/mock"
)

// NewIntervalTimer creates a new instance of IntervalTimer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntervalTimer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IntervalTimer {
	mock := &IntervalTimer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IntervalTimer is an autogenerated mock type for the IntervalTimer type
type IntervalTimer struct {
	mock.Mock
}

type IntervalTimer_Expecter struct {
	mock *mock.Mock
}

func (_m *IntervalTimer) EXPECT() *IntervalTimer_Expecter {
	return &IntervalTimer_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type IntervalTimer
func (_mock *IntervalTimer) Start(interval time.Duration, handler goutils.TimeoutHandler, oneShort bool) error {
	ret := _mock.Called(interval, handler, oneShort)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration, goutils.TimeoutHandler, bool) error); ok {
		r0 = returnFunc(interval, handler, oneShort)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IntervalTimer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type IntervalTimer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - interval time.Duration
//   - handler goutils.TimeoutHandler
//   - oneShort bool
func (_e *IntervalTimer_Expecter) Start(interval interface{}, handler interface{}, oneShort interface{}) *IntervalTimer_Start_Call {
	return &IntervalTimer_Start_Call{Call: _e.mock.On("Start", interval, handler, oneShort)}
}

func (_c *IntervalTimer_Start_Call) Run(run func(interval time.Duration, handler goutils.TimeoutHandler, oneShort bool)) *IntervalTimer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		var arg1 goutils.TimeoutHandler
		if args[1] != nil {
			arg1 = args[1].(goutils.TimeoutHandler)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IntervalTimer_Start_Call) Return(err error) *IntervalTimer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IntervalTimer_Start_Call) RunAndReturn(run func(interval time.Duration, handler goutils.TimeoutHandler, oneShort bool) error) *IntervalTimer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type IntervalTimer
func (_mock *IntervalTimer) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IntervalTimer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type IntervalTimer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *IntervalTimer_Expecter) Stop() *IntervalTimer_Stop_Call {
	return &IntervalTimer_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *IntervalTimer_Stop_Call) Run(run func()) *IntervalTimer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IntervalTimer_Stop_Call) Return(err error) *IntervalTimer_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IntervalTimer_Stop_Call) RunAndReturn(run func() error) *IntervalTimer_Stop_Call {
	_c.Call.Return(run)
	return _c
}
