// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMessageTopic creates a new instance of MessageTopic. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageTopic(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageTopic {
	mock := &MessageTopic{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageTopic is an autogenerated mock type for the MessageTopic type
type MessageTopic struct {
	mock.Mock
}

type MessageTopic_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageTopic) EXPECT() *MessageTopic_Expecter {
	return &MessageTopic_Expecter{mock: &_m.Mock}
}

// CreateSubscription provides a mock function for the type MessageTopic
func (_mock *MessageTopic) CreateSubscription(ctxt context.Context, subscriber string, bufferLen int) (chan interface{}, error) {
	ret := _mock.Called(ctxt, subscriber, bufferLen)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 chan interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (chan interface{}, error)); ok {
		return returnFunc(ctxt, subscriber, bufferLen)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) chan interface{}); ok {
		r0 = returnFunc(ctxt, subscriber, bufferLen)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctxt, subscriber, bufferLen)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MessageTopic_CreateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscription'
type MessageTopic_CreateSubscription_Call struct {
	*mock.Call
}

// CreateSubscription is a helper method to define mock.On call
//   - ctxt context.Context
//   - subscriber string
//   - bufferLen int
func (_e *MessageTopic_Expecter) CreateSubscription(ctxt interface{}, subscriber interface{}, bufferLen interface{}) *MessageTopic_CreateSubscription_Call {
	return &MessageTopic_CreateSubscription_Call{Call: _e.mock.On("CreateSubscription", ctxt, subscriber, bufferLen)}
}

func (_c *MessageTopic_CreateSubscription_Call) Run(run func(ctxt context.Context, subscriber string, bufferLen int)) *MessageTopic_CreateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MessageTopic_CreateSubscription_Call) Return(ifaceValCh chan interface{}, err error) *MessageTopic_CreateSubscription_Call {
	_c.Call.Return(ifaceValCh, err)
	return _c
}

func (_c *MessageTopic_CreateSubscription_Call) RunAndReturn(run func(ctxt context.Context, subscriber string, bufferLen int) (chan interface{}, error)) *MessageTopic_CreateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubscription provides a mock function for the type MessageTopic
func (_mock *MessageTopic) DeleteSubscription(ctxt context.Context, subscriber string) error {
	ret := _mock.Called(ctxt, subscriber)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctxt, subscriber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageTopic_DeleteSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubscription'
type MessageTopic_DeleteSubscription_Call struct {
	*mock.Call
}

// DeleteSubscription is a helper method to define mock.On call
//   - ctxt context.Context
//   - subscriber string
func (_e *MessageTopic_Expecter) DeleteSubscription(ctxt interface{}, subscriber interface{}) *MessageTopic_DeleteSubscription_Call {
	return &MessageTopic_DeleteSubscription_Call{Call: _e.mock.On("DeleteSubscription", ctxt, subscriber)}
}

func (_c *MessageTopic_DeleteSubscription_Call) Run(run func(ctxt context.Context, subscriber string)) *MessageTopic_DeleteSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageTopic_DeleteSubscription_Call) Return(err error) *MessageTopic_DeleteSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageTopic_DeleteSubscription_Call) RunAndReturn(run func(ctxt context.Context, subscriber string) error) *MessageTopic_DeleteSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MessageTopic
func (_mock *MessageTopic) Publish(ctxt context.Context, message interface{}, blockFor time.Duration) error {
	ret := _mock.Called(ctxt, message, blockFor)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, time.Duration) error); ok {
		r0 = returnFunc(ctxt, message, blockFor)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageTopic_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MessageTopic_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctxt context.Context
//   - message interface{}
//   - blockFor time.Duration
func (_e *MessageTopic_Expecter) Publish(ctxt interface{}, message interface{}, blockFor interface{}) *MessageTopic_Publish_Call {
	return &MessageTopic_Publish_Call{Call: _e.mock.On("Publish", ctxt, message, blockFor)}
}

func (_c *MessageTopic_Publish_Call) Run(run func(ctxt context.Context, message interface{}, blockFor time.Duration)) *MessageTopic_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MessageTopic_Publish_Call) Return(err error) *MessageTopic_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageTopic_Publish_Call) RunAndReturn(run func(ctxt context.Context, message interface{}, blockFor time.Duration) error) *MessageTopic_Publish_Call {
	_c.Call.Return(run)
	return _c
}
