// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"context"

	"github.com/alwitt/goutils"
	"github.com/apex/log"
	mock "github.com/stretchr/testify/mock"
)

// NewMessageBus creates a new instance of MessageBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageBus {
	mock := &MessageBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageBus is an autogenerated mock type for the MessageBus type
type MessageBus struct {
	mock.Mock
}

type MessageBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageBus) EXPECT() *MessageBus_Expecter {
	return &MessageBus_Expecter{mock: &_m.Mock}
}

// CreateTopic provides a mock function for the type MessageBus
func (_mock *MessageBus) CreateTopic(ctxt context.Context, topicName string, topicLogTags log.Fields) (goutils.MessageTopic, error) {
	ret := _mock.Called(ctxt, topicName, topicLogTags)

	if len(ret) == 0 {
		panic("no return value specified for CreateTopic")
	}

	var r0 goutils.MessageTopic
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, log.Fields) (goutils.MessageTopic, error)); ok {
		return returnFunc(ctxt, topicName, topicLogTags)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, log.Fields) goutils.MessageTopic); ok {
		r0 = returnFunc(ctxt, topicName, topicLogTags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goutils.MessageTopic)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, log.Fields) error); ok {
		r1 = returnFunc(ctxt, topicName, topicLogTags)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MessageBus_CreateTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTopic'
type MessageBus_CreateTopic_Call struct {
	*mock.Call
}

// CreateTopic is a helper method to define mock.On call
//   - ctxt context.Context
//   - topicName string
//   - topicLogTags log.Fields
func (_e *MessageBus_Expecter) CreateTopic(ctxt interface{}, topicName interface{}, topicLogTags interface{}) *MessageBus_CreateTopic_Call {
	return &MessageBus_CreateTopic_Call{Call: _e.mock.On("CreateTopic", ctxt, topicName, topicLogTags)}
}

func (_c *MessageBus_CreateTopic_Call) Run(run func(ctxt context.Context, topicName string, topicLogTags log.Fields)) *MessageBus_CreateTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 log.Fields
		if args[2] != nil {
			arg2 = args[2].(log.Fields)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MessageBus_CreateTopic_Call) Return(messageTopic goutils.MessageTopic, err error) *MessageBus_CreateTopic_Call {
	_c.Call.Return(messageTopic, err)
	return _c
}

func (_c *MessageBus_CreateTopic_Call) RunAndReturn(run func(ctxt context.Context, topicName string, topicLogTags log.Fields) (goutils.MessageTopic, error)) *MessageBus_CreateTopic_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTopic provides a mock function for the type MessageBus
func (_mock *MessageBus) DeleteTopic(ctxt context.Context, topicName string) error {
	ret := _mock.Called(ctxt, topicName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTopic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctxt, topicName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageBus_DeleteTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTopic'
type MessageBus_DeleteTopic_Call struct {
	*mock.Call
}

// DeleteTopic is a helper method to define mock.On call
//   - ctxt context.Context
//   - topicName string
func (_e *MessageBus_Expecter) DeleteTopic(ctxt interface{}, topicName interface{}) *MessageBus_DeleteTopic_Call {
	return &MessageBus_DeleteTopic_Call{Call: _e.mock.On("DeleteTopic", ctxt, topicName)}
}

func (_c *MessageBus_DeleteTopic_Call) Run(run func(ctxt context.Context, topicName string)) *MessageBus_DeleteTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageBus_DeleteTopic_Call) Return(err error) *MessageBus_DeleteTopic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageBus_DeleteTopic_Call) RunAndReturn(run func(ctxt context.Context, topicName string) error) *MessageBus_DeleteTopic_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopic provides a mock function for the type MessageBus
func (_mock *MessageBus) GetTopic(ctxt context.Context, topicName string) (goutils.MessageTopic, error) {
	ret := _mock.Called(ctxt, topicName)

	if len(ret) == 0 {
		panic("no return value specified for GetTopic")
	}

	var r0 goutils.MessageTopic
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (goutils.MessageTopic, error)); ok {
		return returnFunc(ctxt, topicName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) goutils.MessageTopic); ok {
		r0 = returnFunc(ctxt, topicName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goutils.MessageTopic)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctxt, topicName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MessageBus_GetTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopic'
type MessageBus_GetTopic_Call struct {
	*mock.Call
}

// GetTopic is a helper method to define mock.On call
//   - ctxt context.Context
//   - topicName string
func (_e *MessageBus_Expecter) GetTopic(ctxt interface{}, topicName interface{}) *MessageBus_GetTopic_Call {
	return &MessageBus_GetTopic_Call{Call: _e.mock.On("GetTopic", ctxt, topicName)}
}

func (_c *MessageBus_GetTopic_Call) Run(run func(ctxt context.Context, topicName string)) *MessageBus_GetTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageBus_GetTopic_Call) Return(messageTopic goutils.MessageTopic, err error) *MessageBus_GetTopic_Call {
	_c.Call.Return(messageTopic, err)
	return _c
}

func (_c *MessageBus_GetTopic_Call) RunAndReturn(run func(ctxt context.Context, topicName string) (goutils.MessageTopic, error)) *MessageBus_GetTopic_Call {
	_c.Call.Return(run)
	return _c
}
