// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"context"

	"github.com/alwitt/goutils"
	"github.com/gorilla/mux"
	"github.com/prometheus/client_golang/prometheus"
	mock "github.com/stretchr/testify/mock"
)

// NewMetricsCollector creates a new instance of MetricsCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsCollector {
	mock := &MetricsCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MetricsCollector is an autogenerated mock type for the MetricsCollector type
type MetricsCollector struct {
	mock.Mock
}

type MetricsCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsCollector) EXPECT() *MetricsCollector_Expecter {
	return &MetricsCollector_Expecter{mock: &_m.Mock}
}

// ExposeCollectionEndpoint provides a mock function for the type MetricsCollector
func (_mock *MetricsCollector) ExposeCollectionEndpoint(router *mux.Router, metricsPath string, maxSupportedRequest int) {
	_mock.Called(router, metricsPath, maxSupportedRequest)
	return
}

// MetricsCollector_ExposeCollectionEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExposeCollectionEndpoint'
type MetricsCollector_ExposeCollectionEndpoint_Call struct {
	*mock.Call
}

// ExposeCollectionEndpoint is a helper method to define mock.On call
//   - router *mux.Router
//   - metricsPath string
//   - maxSupportedRequest int
func (_e *MetricsCollector_Expecter) ExposeCollectionEndpoint(router interface{}, metricsPath interface{}, maxSupportedRequest interface{}) *MetricsCollector_ExposeCollectionEndpoint_Call {
	return &MetricsCollector_ExposeCollectionEndpoint_Call{Call: _e.mock.On("ExposeCollectionEndpoint", router, metricsPath, maxSupportedRequest)}
}

func (_c *MetricsCollector_ExposeCollectionEndpoint_Call) Run(run func(router *mux.Router, metricsPath string, maxSupportedRequest int)) *MetricsCollector_ExposeCollectionEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mux.Router
		if args[0] != nil {
			arg0 = args[0].(*mux.Router)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MetricsCollector_ExposeCollectionEndpoint_Call) Return() *MetricsCollector_ExposeCollectionEndpoint_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsCollector_ExposeCollectionEndpoint_Call) RunAndReturn(run func(router *mux.Router, metricsPath string, maxSupportedRequest int)) *MetricsCollector_ExposeCollectionEndpoint_Call {
	_c.Run(run)
	return _c
}

// InstallApplicationMetrics provides a mock function for the type MetricsCollector
func (_mock *MetricsCollector) InstallApplicationMetrics() {
	_mock.Called()
	return
}

// MetricsCollector_InstallApplicationMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallApplicationMetrics'
type MetricsCollector_InstallApplicationMetrics_Call struct {
	*mock.Call
}

// InstallApplicationMetrics is a helper method to define mock.On call
func (_e *MetricsCollector_Expecter) InstallApplicationMetrics() *MetricsCollector_InstallApplicationMetrics_Call {
	return &MetricsCollector_InstallApplicationMetrics_Call{Call: _e.mock.On("InstallApplicationMetrics")}
}

func (_c *MetricsCollector_InstallApplicationMetrics_Call) Run(run func()) *MetricsCollector_InstallApplicationMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricsCollector_InstallApplicationMetrics_Call) Return() *MetricsCollector_InstallApplicationMetrics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsCollector_InstallApplicationMetrics_Call) RunAndReturn(run func()) *MetricsCollector_InstallApplicationMetrics_Call {
	_c.Run(run)
	return _c
}

// InstallCustomCounterVecMetrics provides a mock function for the type MetricsCollector
func (_mock *MetricsCollector) InstallCustomCounterVecMetrics(ctxt context.Context, metricsName string, metricsHelpMessage string, metricsLabels []string) (*prometheus.CounterVec, error) {
	ret := _mock.Called(ctxt, metricsName, metricsHelpMessage, metricsLabels)

	if len(ret) == 0 {
		panic("no return value specified for InstallCustomCounterVecMetrics")
	}

	var r0 *prometheus.CounterVec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) (*prometheus.CounterVec, error)); ok {
		return returnFunc(ctxt, metricsName, metricsHelpMessage, metricsLabels)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) *prometheus.CounterVec); ok {
		r0 = returnFunc(ctxt, metricsName, metricsHelpMessage, metricsLabels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prometheus.CounterVec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = returnFunc(ctxt, metricsName, metricsHelpMessage, metricsLabels)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsCollector_InstallCustomCounterVecMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallCustomCounterVecMetrics'
type MetricsCollector_InstallCustomCounterVecMetrics_Call struct {
	*mock.Call
}

// InstallCustomCounterVecMetrics is a helper method to define mock.On call
//   - ctxt context.Context
//   - metricsName string
//   - metricsHelpMessage string
//   - metricsLabels []string
func (_e *MetricsCollector_Expecter) InstallCustomCounterVecMetrics(ctxt interface{}, metricsName interface{}, metricsHelpMessage interface{}, metricsLabels interface{}) *MetricsCollector_InstallCustomCounterVecMetrics_Call {
	return &MetricsCollector_InstallCustomCounterVecMetrics_Call{Call: _e.mock.On("InstallCustomCounterVecMetrics", ctxt, metricsName, metricsHelpMessage, metricsLabels)}
}

func (_c *MetricsCollector_InstallCustomCounterVecMetrics_Call) Run(run func(ctxt context.Context, metricsName string, metricsHelpMessage string, metricsLabels []string)) *MetricsCollector_InstallCustomCounterVecMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MetricsCollector_InstallCustomCounterVecMetrics_Call) Return(counterVec *prometheus.CounterVec, err error) *MetricsCollector_InstallCustomCounterVecMetrics_Call {
	_c.Call.Return(counterVec, err)
	return _c
}

func (_c *MetricsCollector_InstallCustomCounterVecMetrics_Call) RunAndReturn(run func(ctxt context.Context, metricsName string, metricsHelpMessage string, metricsLabels []string) (*prometheus.CounterVec, error)) *MetricsCollector_InstallCustomCounterVecMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// InstallCustomGaugeVecMetrics provides a mock function for the type MetricsCollector
func (_mock *MetricsCollector) InstallCustomGaugeVecMetrics(ctxt context.Context, metricsName string, metricsHelpMessage string, metricsLabels []string) (*prometheus.GaugeVec, error) {
	ret := _mock.Called(ctxt, metricsName, metricsHelpMessage, metricsLabels)

	if len(ret) == 0 {
		panic("no return value specified for InstallCustomGaugeVecMetrics")
	}

	var r0 *prometheus.GaugeVec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) (*prometheus.GaugeVec, error)); ok {
		return returnFunc(ctxt, metricsName, metricsHelpMessage, metricsLabels)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) *prometheus.GaugeVec); ok {
		r0 = returnFunc(ctxt, metricsName, metricsHelpMessage, metricsLabels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prometheus.GaugeVec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = returnFunc(ctxt, metricsName, metricsHelpMessage, metricsLabels)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsCollector_InstallCustomGaugeVecMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallCustomGaugeVecMetrics'
type MetricsCollector_InstallCustomGaugeVecMetrics_Call struct {
	*mock.Call
}

// InstallCustomGaugeVecMetrics is a helper method to define mock.On call
//   - ctxt context.Context
//   - metricsName string
//   - metricsHelpMessage string
//   - metricsLabels []string
func (_e *MetricsCollector_Expecter) InstallCustomGaugeVecMetrics(ctxt interface{}, metricsName interface{}, metricsHelpMessage interface{}, metricsLabels interface{}) *MetricsCollector_InstallCustomGaugeVecMetrics_Call {
	return &MetricsCollector_InstallCustomGaugeVecMetrics_Call{Call: _e.mock.On("InstallCustomGaugeVecMetrics", ctxt, metricsName, metricsHelpMessage, metricsLabels)}
}

func (_c *MetricsCollector_InstallCustomGaugeVecMetrics_Call) Run(run func(ctxt context.Context, metricsName string, metricsHelpMessage string, metricsLabels []string)) *MetricsCollector_InstallCustomGaugeVecMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MetricsCollector_InstallCustomGaugeVecMetrics_Call) Return(gaugeVec *prometheus.GaugeVec, err error) *MetricsCollector_InstallCustomGaugeVecMetrics_Call {
	_c.Call.Return(gaugeVec, err)
	return _c
}

func (_c *MetricsCollector_InstallCustomGaugeVecMetrics_Call) RunAndReturn(run func(ctxt context.Context, metricsName string, metricsHelpMessage string, metricsLabels []string) (*prometheus.GaugeVec, error)) *MetricsCollector_InstallCustomGaugeVecMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// InstallHTTPMetrics provides a mock function for the type MetricsCollector
func (_mock *MetricsCollector) InstallHTTPMetrics() goutils.HTTPRequestMetricHelper {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstallHTTPMetrics")
	}

	var r0 goutils.HTTPRequestMetricHelper
	if returnFunc, ok := ret.Get(0).(func() goutils.HTTPRequestMetricHelper); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goutils.HTTPRequestMetricHelper)
		}
	}
	return r0
}

// MetricsCollector_InstallHTTPMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallHTTPMetrics'
type MetricsCollector_InstallHTTPMetrics_Call struct {
	*mock.Call
}

// InstallHTTPMetrics is a helper method to define mock.On call
func (_e *MetricsCollector_Expecter) InstallHTTPMetrics() *MetricsCollector_InstallHTTPMetrics_Call {
	return &MetricsCollector_InstallHTTPMetrics_Call{Call: _e.mock.On("InstallHTTPMetrics")}
}

func (_c *MetricsCollector_InstallHTTPMetrics_Call) Run(run func()) *MetricsCollector_InstallHTTPMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricsCollector_InstallHTTPMetrics_Call) Return(hTTPRequestMetricHelper goutils.HTTPRequestMetricHelper) *MetricsCollector_InstallHTTPMetrics_Call {
	_c.Call.Return(hTTPRequestMetricHelper)
	return _c
}

func (_c *MetricsCollector_InstallHTTPMetrics_Call) RunAndReturn(run func() goutils.HTTPRequestMetricHelper) *MetricsCollector_InstallHTTPMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// InstallPubSubMetrics provides a mock function for the type MetricsCollector
func (_mock *MetricsCollector) InstallPubSubMetrics() goutils.PubSubMetricHelper {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstallPubSubMetrics")
	}

	var r0 goutils.PubSubMetricHelper
	if returnFunc, ok := ret.Get(0).(func() goutils.PubSubMetricHelper); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goutils.PubSubMetricHelper)
		}
	}
	return r0
}

// MetricsCollector_InstallPubSubMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallPubSubMetrics'
type MetricsCollector_InstallPubSubMetrics_Call struct {
	*mock.Call
}

// InstallPubSubMetrics is a helper method to define mock.On call
func (_e *MetricsCollector_Expecter) InstallPubSubMetrics() *MetricsCollector_InstallPubSubMetrics_Call {
	return &MetricsCollector_InstallPubSubMetrics_Call{Call: _e.mock.On("InstallPubSubMetrics")}
}

func (_c *MetricsCollector_InstallPubSubMetrics_Call) Run(run func()) *MetricsCollector_InstallPubSubMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricsCollector_InstallPubSubMetrics_Call) Return(pubSubMetricHelper goutils.PubSubMetricHelper) *MetricsCollector_InstallPubSubMetrics_Call {
	_c.Call.Return(pubSubMetricHelper)
	return _c
}

func (_c *MetricsCollector_InstallPubSubMetrics_Call) RunAndReturn(run func() goutils.PubSubMetricHelper) *MetricsCollector_InstallPubSubMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// InstallTaskProcessorMetrics provides a mock function for the type MetricsCollector
func (_mock *MetricsCollector) InstallTaskProcessorMetrics() goutils.TaskProcessorMetricHelper {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstallTaskProcessorMetrics")
	}

	var r0 goutils.TaskProcessorMetricHelper
	if returnFunc, ok := ret.Get(0).(func() goutils.TaskProcessorMetricHelper); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goutils.TaskProcessorMetricHelper)
		}
	}
	return r0
}

// MetricsCollector_InstallTaskProcessorMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallTaskProcessorMetrics'
type MetricsCollector_InstallTaskProcessorMetrics_Call struct {
	*mock.Call
}

// InstallTaskProcessorMetrics is a helper method to define mock.On call
func (_e *MetricsCollector_Expecter) InstallTaskProcessorMetrics() *MetricsCollector_InstallTaskProcessorMetrics_Call {
	return &MetricsCollector_InstallTaskProcessorMetrics_Call{Call: _e.mock.On("InstallTaskProcessorMetrics")}
}

func (_c *MetricsCollector_InstallTaskProcessorMetrics_Call) Run(run func()) *MetricsCollector_InstallTaskProcessorMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricsCollector_InstallTaskProcessorMetrics_Call) Return(taskProcessorMetricHelper goutils.TaskProcessorMetricHelper) *MetricsCollector_InstallTaskProcessorMetrics_Call {
	_c.Call.Return(taskProcessorMetricHelper)
	return _c
}

func (_c *MetricsCollector_InstallTaskProcessorMetrics_Call) RunAndReturn(run func() goutils.TaskProcessorMetricHelper) *MetricsCollector_InstallTaskProcessorMetrics_Call {
	_c.Call.Return(run)
	return _c
}
