// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewOAuthTokenManager creates a new instance of OAuthTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuthTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuthTokenManager {
	mock := &OAuthTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuthTokenManager is an autogenerated mock type for the OAuthTokenManager type
type OAuthTokenManager struct {
	mock.Mock
}

type OAuthTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuthTokenManager) EXPECT() *OAuthTokenManager_Expecter {
	return &OAuthTokenManager_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function for the type OAuthTokenManager
func (_mock *OAuthTokenManager) GetToken(ctxt context.Context, timestamp time.Time) (string, error) {
	ret := _mock.Called(ctxt, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (string, error)); ok {
		return returnFunc(ctxt, timestamp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) string); ok {
		r0 = returnFunc(ctxt, timestamp)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctxt, timestamp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthTokenManager_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type OAuthTokenManager_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctxt context.Context
//   - timestamp time.Time
func (_e *OAuthTokenManager_Expecter) GetToken(ctxt interface{}, timestamp interface{}) *OAuthTokenManager_GetToken_Call {
	return &OAuthTokenManager_GetToken_Call{Call: _e.mock.On("GetToken", ctxt, timestamp)}
}

func (_c *OAuthTokenManager_GetToken_Call) Run(run func(ctxt context.Context, timestamp time.Time)) *OAuthTokenManager_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthTokenManager_GetToken_Call) Return(s string, err error) *OAuthTokenManager_GetToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *OAuthTokenManager_GetToken_Call) RunAndReturn(run func(ctxt context.Context, timestamp time.Time) (string, error)) *OAuthTokenManager_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type OAuthTokenManager
func (_mock *OAuthTokenManager) Stop(ctxt context.Context) error {
	ret := _mock.Called(ctxt)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctxt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OAuthTokenManager_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type OAuthTokenManager_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctxt context.Context
func (_e *OAuthTokenManager_Expecter) Stop(ctxt interface{}) *OAuthTokenManager_Stop_Call {
	return &OAuthTokenManager_Stop_Call{Call: _e.mock.On("Stop", ctxt)}
}

func (_c *OAuthTokenManager_Stop_Call) Run(run func(ctxt context.Context)) *OAuthTokenManager_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OAuthTokenManager_Stop_Call) Return(err error) *OAuthTokenManager_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OAuthTokenManager_Stop_Call) RunAndReturn(run func(ctxt context.Context) error) *OAuthTokenManager_Stop_Call {
	_c.Call.Return(run)
	return _c
}
