// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"context"

	"github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewOpenIDProviderClient creates a new instance of OpenIDProviderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOpenIDProviderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *OpenIDProviderClient {
	mock := &OpenIDProviderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OpenIDProviderClient is an autogenerated mock type for the OpenIDProviderClient type
type OpenIDProviderClient struct {
	mock.Mock
}

type OpenIDProviderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *OpenIDProviderClient) EXPECT() *OpenIDProviderClient_Expecter {
	return &OpenIDProviderClient_Expecter{mock: &_m.Mock}
}

// AssociatedPublicKey provides a mock function for the type OpenIDProviderClient
func (_mock *OpenIDProviderClient) AssociatedPublicKey(token *jwt.Token) (interface{}, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for AssociatedPublicKey")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*jwt.Token) (interface{}, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(*jwt.Token) interface{}); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*jwt.Token) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenIDProviderClient_AssociatedPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssociatedPublicKey'
type OpenIDProviderClient_AssociatedPublicKey_Call struct {
	*mock.Call
}

// AssociatedPublicKey is a helper method to define mock.On call
//   - token *jwt.Token
func (_e *OpenIDProviderClient_Expecter) AssociatedPublicKey(token interface{}) *OpenIDProviderClient_AssociatedPublicKey_Call {
	return &OpenIDProviderClient_AssociatedPublicKey_Call{Call: _e.mock.On("AssociatedPublicKey", token)}
}

func (_c *OpenIDProviderClient_AssociatedPublicKey_Call) Run(run func(token *jwt.Token)) *OpenIDProviderClient_AssociatedPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *jwt.Token
		if args[0] != nil {
			arg0 = args[0].(*jwt.Token)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OpenIDProviderClient_AssociatedPublicKey_Call) Return(ifaceVal interface{}, err error) *OpenIDProviderClient_AssociatedPublicKey_Call {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *OpenIDProviderClient_AssociatedPublicKey_Call) RunAndReturn(run func(token *jwt.Token) (interface{}, error)) *OpenIDProviderClient_AssociatedPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// CanIntrospect provides a mock function for the type OpenIDProviderClient
func (_mock *OpenIDProviderClient) CanIntrospect() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanIntrospect")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// OpenIDProviderClient_CanIntrospect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanIntrospect'
type OpenIDProviderClient_CanIntrospect_Call struct {
	*mock.Call
}

// CanIntrospect is a helper method to define mock.On call
func (_e *OpenIDProviderClient_Expecter) CanIntrospect() *OpenIDProviderClient_CanIntrospect_Call {
	return &OpenIDProviderClient_CanIntrospect_Call{Call: _e.mock.On("CanIntrospect")}
}

func (_c *OpenIDProviderClient_CanIntrospect_Call) Run(run func()) *OpenIDProviderClient_CanIntrospect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OpenIDProviderClient_CanIntrospect_Call) Return(b bool) *OpenIDProviderClient_CanIntrospect_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *OpenIDProviderClient_CanIntrospect_Call) RunAndReturn(run func() bool) *OpenIDProviderClient_CanIntrospect_Call {
	_c.Call.Return(run)
	return _c
}

// IntrospectToken provides a mock function for the type OpenIDProviderClient
func (_mock *OpenIDProviderClient) IntrospectToken(ctxt context.Context, token string) (bool, error) {
	ret := _mock.Called(ctxt, token)

	if len(ret) == 0 {
		panic("no return value specified for IntrospectToken")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctxt, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctxt, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctxt, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenIDProviderClient_IntrospectToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntrospectToken'
type OpenIDProviderClient_IntrospectToken_Call struct {
	*mock.Call
}

// IntrospectToken is a helper method to define mock.On call
//   - ctxt context.Context
//   - token string
func (_e *OpenIDProviderClient_Expecter) IntrospectToken(ctxt interface{}, token interface{}) *OpenIDProviderClient_IntrospectToken_Call {
	return &OpenIDProviderClient_IntrospectToken_Call{Call: _e.mock.On("IntrospectToken", ctxt, token)}
}

func (_c *OpenIDProviderClient_IntrospectToken_Call) Run(run func(ctxt context.Context, token string)) *OpenIDProviderClient_IntrospectToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenIDProviderClient_IntrospectToken_Call) Return(b bool, err error) *OpenIDProviderClient_IntrospectToken_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *OpenIDProviderClient_IntrospectToken_Call) RunAndReturn(run func(ctxt context.Context, token string) (bool, error)) *OpenIDProviderClient_IntrospectToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseJWT provides a mock function for the type OpenIDProviderClient
func (_mock *OpenIDProviderClient) ParseJWT(raw string, claimStore jwt.Claims) (*jwt.Token, error) {
	ret := _mock.Called(raw, claimStore)

	if len(ret) == 0 {
		panic("no return value specified for ParseJWT")
	}

	var r0 *jwt.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Claims) (*jwt.Token, error)); ok {
		return returnFunc(raw, claimStore)
	}
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Claims) *jwt.Token); ok {
		r0 = returnFunc(raw, claimStore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, jwt.Claims) error); ok {
		r1 = returnFunc(raw, claimStore)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenIDProviderClient_ParseJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseJWT'
type OpenIDProviderClient_ParseJWT_Call struct {
	*mock.Call
}

// ParseJWT is a helper method to define mock.On call
//   - raw string
//   - claimStore jwt.Claims
func (_e *OpenIDProviderClient_Expecter) ParseJWT(raw interface{}, claimStore interface{}) *OpenIDProviderClient_ParseJWT_Call {
	return &OpenIDProviderClient_ParseJWT_Call{Call: _e.mock.On("ParseJWT", raw, claimStore)}
}

func (_c *OpenIDProviderClient_ParseJWT_Call) Run(run func(raw string, claimStore jwt.Claims)) *OpenIDProviderClient_ParseJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 jwt.Claims
		if args[1] != nil {
			arg1 = args[1].(jwt.Claims)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenIDProviderClient_ParseJWT_Call) Return(token *jwt.Token, err error) *OpenIDProviderClient_ParseJWT_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *OpenIDProviderClient_ParseJWT_Call) RunAndReturn(run func(raw string, claimStore jwt.Claims) (*jwt.Token, error)) *OpenIDProviderClient_ParseJWT_Call {
	_c.Call.Return(run)
	return _c
}
