// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"github.com/alwitt/goutils"
	mock "github.com/stretchr/testify/mock"
)

// NewPriorityQueueEntry creates a new instance of PriorityQueueEntry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriorityQueueEntry(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriorityQueueEntry {
	mock := &PriorityQueueEntry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PriorityQueueEntry is an autogenerated mock type for the PriorityQueueEntry type
type PriorityQueueEntry struct {
	mock.Mock
}

type PriorityQueueEntry_Expecter struct {
	mock *mock.Mock
}

func (_m *PriorityQueueEntry) EXPECT() *PriorityQueueEntry_Expecter {
	return &PriorityQueueEntry_Expecter{mock: &_m.Mock}
}

// HigherPriorityThan provides a mock function for the type PriorityQueueEntry
func (_mock *PriorityQueueEntry) HigherPriorityThan(right goutils.PriorityQueueEntry) bool {
	ret := _mock.Called(right)

	if len(ret) == 0 {
		panic("no return value specified for HigherPriorityThan")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(goutils.PriorityQueueEntry) bool); ok {
		r0 = returnFunc(right)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// PriorityQueueEntry_HigherPriorityThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HigherPriorityThan'
type PriorityQueueEntry_HigherPriorityThan_Call struct {
	*mock.Call
}

// HigherPriorityThan is a helper method to define mock.On call
//   - right goutils.PriorityQueueEntry
func (_e *PriorityQueueEntry_Expecter) HigherPriorityThan(right interface{}) *PriorityQueueEntry_HigherPriorityThan_Call {
	return &PriorityQueueEntry_HigherPriorityThan_Call{Call: _e.mock.On("HigherPriorityThan", right)}
}

func (_c *PriorityQueueEntry_HigherPriorityThan_Call) Run(run func(right goutils.PriorityQueueEntry)) *PriorityQueueEntry_HigherPriorityThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 goutils.PriorityQueueEntry
		if args[0] != nil {
			arg0 = args[0].(goutils.PriorityQueueEntry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PriorityQueueEntry_HigherPriorityThan_Call) Return(b bool) *PriorityQueueEntry_HigherPriorityThan_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *PriorityQueueEntry_HigherPriorityThan_Call) RunAndReturn(run func(right goutils.PriorityQueueEntry) bool) *PriorityQueueEntry_HigherPriorityThan_Call {
	_c.Call.Return(run)
	return _c
}
