// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPubSubMetricHelper creates a new instance of PubSubMetricHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPubSubMetricHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *PubSubMetricHelper {
	mock := &PubSubMetricHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PubSubMetricHelper is an autogenerated mock type for the PubSubMetricHelper type
type PubSubMetricHelper struct {
	mock.Mock
}

type PubSubMetricHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *PubSubMetricHelper) EXPECT() *PubSubMetricHelper_Expecter {
	return &PubSubMetricHelper_Expecter{mock: &_m.Mock}
}

// RecordPublish provides a mock function for the type PubSubMetricHelper
func (_mock *PubSubMetricHelper) RecordPublish(topic string, successful bool, payloadLen int64) {
	_mock.Called(topic, successful, payloadLen)
	return
}

// PubSubMetricHelper_RecordPublish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordPublish'
type PubSubMetricHelper_RecordPublish_Call struct {
	*mock.Call
}

// RecordPublish is a helper method to define mock.On call
//   - topic string
//   - successful bool
//   - payloadLen int64
func (_e *PubSubMetricHelper_Expecter) RecordPublish(topic interface{}, successful interface{}, payloadLen interface{}) *PubSubMetricHelper_RecordPublish_Call {
	return &PubSubMetricHelper_RecordPublish_Call{Call: _e.mock.On("RecordPublish", topic, successful, payloadLen)}
}

func (_c *PubSubMetricHelper_RecordPublish_Call) Run(run func(topic string, successful bool, payloadLen int64)) *PubSubMetricHelper_RecordPublish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PubSubMetricHelper_RecordPublish_Call) Return() *PubSubMetricHelper_RecordPublish_Call {
	_c.Call.Return()
	return _c
}

func (_c *PubSubMetricHelper_RecordPublish_Call) RunAndReturn(run func(topic string, successful bool, payloadLen int64)) *PubSubMetricHelper_RecordPublish_Call {
	_c.Run(run)
	return _c
}

// RecordReceive provides a mock function for the type PubSubMetricHelper
func (_mock *PubSubMetricHelper) RecordReceive(topic string, successful bool, payloadLen int64) {
	_mock.Called(topic, successful, payloadLen)
	return
}

// PubSubMetricHelper_RecordReceive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordReceive'
type PubSubMetricHelper_RecordReceive_Call struct {
	*mock.Call
}

// RecordReceive is a helper method to define mock.On call
//   - topic string
//   - successful bool
//   - payloadLen int64
func (_e *PubSubMetricHelper_Expecter) RecordReceive(topic interface{}, successful interface{}, payloadLen interface{}) *PubSubMetricHelper_RecordReceive_Call {
	return &PubSubMetricHelper_RecordReceive_Call{Call: _e.mock.On("RecordReceive", topic, successful, payloadLen)}
}

func (_c *PubSubMetricHelper_RecordReceive_Call) Run(run func(topic string, successful bool, payloadLen int64)) *PubSubMetricHelper_RecordReceive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PubSubMetricHelper_RecordReceive_Call) Return() *PubSubMetricHelper_RecordReceive_Call {
	_c.Call.Return()
	return _c
}

func (_c *PubSubMetricHelper_RecordReceive_Call) RunAndReturn(run func(topic string, successful bool, payloadLen int64)) *PubSubMetricHelper_RecordReceive_Call {
	_c.Run(run)
	return _c
}
