// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	mock "github.com/stretchr/testify/mock"
)

// NewQueue creates a new instance of Queue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueue[V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Queue[V] {
	mock := &Queue[V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Queue is an autogenerated mock type for the Queue type
type Queue[V any] struct {
	mock.Mock
}

type Queue_Expecter[V any] struct {
	mock *mock.Mock
}

func (_m *Queue[V]) EXPECT() *Queue_Expecter[V] {
	return &Queue_Expecter[V]{mock: &_m.Mock}
}

// Len provides a mock function for the type Queue
func (_mock *Queue[V]) Len() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// Queue_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type Queue_Len_Call[V any] struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *Queue_Expecter[V]) Len() *Queue_Len_Call[V] {
	return &Queue_Len_Call[V]{Call: _e.mock.On("Len")}
}

func (_c *Queue_Len_Call[V]) Run(run func()) *Queue_Len_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Queue_Len_Call[V]) Return(n int) *Queue_Len_Call[V] {
	_c.Call.Return(n)
	return _c
}

func (_c *Queue_Len_Call[V]) RunAndReturn(run func() int) *Queue_Len_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Pop provides a mock function for the type Queue
func (_mock *Queue[V]) Pop() (V, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pop")
	}

	var r0 V
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (V, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() V); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_Pop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pop'
type Queue_Pop_Call[V any] struct {
	*mock.Call
}

// Pop is a helper method to define mock.On call
func (_e *Queue_Expecter[V]) Pop() *Queue_Pop_Call[V] {
	return &Queue_Pop_Call[V]{Call: _e.mock.On("Pop")}
}

func (_c *Queue_Pop_Call[V]) Run(run func()) *Queue_Pop_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Queue_Pop_Call[V]) Return(v V, err error) *Queue_Pop_Call[V] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Queue_Pop_Call[V]) RunAndReturn(run func() (V, error)) *Queue_Pop_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type Queue
func (_mock *Queue[V]) Push(data V) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(V) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queue_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type Queue_Push_Call[V any] struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - data V
func (_e *Queue_Expecter[V]) Push(data interface{}) *Queue_Push_Call[V] {
	return &Queue_Push_Call[V]{Call: _e.mock.On("Push", data)}
}

func (_c *Queue_Push_Call[V]) Run(run func(data V)) *Queue_Push_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 V
		if args[0] != nil {
			arg0 = args[0].(V)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Queue_Push_Call[V]) Return(err error) *Queue_Push_Call[V] {
	_c.Call.Return(err)
	return _c
}

func (_c *Queue_Push_Call[V]) RunAndReturn(run func(data V) error) *Queue_Push_Call[V] {
	_c.Call.Return(run)
	return _c
}
