// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"context"
	"io"
	"net/url"
	"time"

	"github.com/alwitt/goutils"
	mock "github.com/stretchr/testify/mock"
)

// NewS3Client creates a new instance of S3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3Client {
	mock := &S3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// S3Client is an autogenerated mock type for the S3Client type
type S3Client struct {
	mock.Mock
}

type S3Client_Expecter struct {
	mock *mock.Mock
}

func (_m *S3Client) EXPECT() *S3Client_Expecter {
	return &S3Client_Expecter{mock: &_m.Mock}
}

// CopyObject provides a mock function for the type S3Client
func (_mock *S3Client) CopyObject(ctx context.Context, srcBucket string, srcKey string, dstBucket string, dstKey string, newMIMEType *string) error {
	ret := _mock.Called(ctx, srcBucket, srcKey, dstBucket, dstKey, newMIMEType)

	if len(ret) == 0 {
		panic("no return value specified for CopyObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, *string) error); ok {
		r0 = returnFunc(ctx, srcBucket, srcKey, dstBucket, dstKey, newMIMEType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// S3Client_CopyObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyObject'
type S3Client_CopyObject_Call struct {
	*mock.Call
}

// CopyObject is a helper method to define mock.On call
//   - ctx context.Context
//   - srcBucket string
//   - srcKey string
//   - dstBucket string
//   - dstKey string
//   - newMIMEType *string
func (_e *S3Client_Expecter) CopyObject(ctx interface{}, srcBucket interface{}, srcKey interface{}, dstBucket interface{}, dstKey interface{}, newMIMEType interface{}) *S3Client_CopyObject_Call {
	return &S3Client_CopyObject_Call{Call: _e.mock.On("CopyObject", ctx, srcBucket, srcKey, dstBucket, dstKey, newMIMEType)}
}

func (_c *S3Client_CopyObject_Call) Run(run func(ctx context.Context, srcBucket string, srcKey string, dstBucket string, dstKey string, newMIMEType *string)) *S3Client_CopyObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *S3Client_CopyObject_Call) Return(err error) *S3Client_CopyObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *S3Client_CopyObject_Call) RunAndReturn(run func(ctx context.Context, srcBucket string, srcKey string, dstBucket string, dstKey string, newMIMEType *string) error) *S3Client_CopyObject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBucket provides a mock function for the type S3Client
func (_mock *S3Client) CreateBucket(ctx context.Context, bucket string) error {
	ret := _mock.Called(ctx, bucket)

	if len(ret) == 0 {
		panic("no return value specified for CreateBucket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bucket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// S3Client_CreateBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBucket'
type S3Client_CreateBucket_Call struct {
	*mock.Call
}

// CreateBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
func (_e *S3Client_Expecter) CreateBucket(ctx interface{}, bucket interface{}) *S3Client_CreateBucket_Call {
	return &S3Client_CreateBucket_Call{Call: _e.mock.On("CreateBucket", ctx, bucket)}
}

func (_c *S3Client_CreateBucket_Call) Run(run func(ctx context.Context, bucket string)) *S3Client_CreateBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *S3Client_CreateBucket_Call) Return(err error) *S3Client_CreateBucket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *S3Client_CreateBucket_Call) RunAndReturn(run func(ctx context.Context, bucket string) error) *S3Client_CreateBucket_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBucket provides a mock function for the type S3Client
func (_mock *S3Client) DeleteBucket(ctx context.Context, bucket string) error {
	ret := _mock.Called(ctx, bucket)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBucket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bucket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// S3Client_DeleteBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBucket'
type S3Client_DeleteBucket_Call struct {
	*mock.Call
}

// DeleteBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
func (_e *S3Client_Expecter) DeleteBucket(ctx interface{}, bucket interface{}) *S3Client_DeleteBucket_Call {
	return &S3Client_DeleteBucket_Call{Call: _e.mock.On("DeleteBucket", ctx, bucket)}
}

func (_c *S3Client_DeleteBucket_Call) Run(run func(ctx context.Context, bucket string)) *S3Client_DeleteBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *S3Client_DeleteBucket_Call) Return(err error) *S3Client_DeleteBucket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *S3Client_DeleteBucket_Call) RunAndReturn(run func(ctx context.Context, bucket string) error) *S3Client_DeleteBucket_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type S3Client
func (_mock *S3Client) DeleteObject(ctx context.Context, bucket string, objectKey string) error {
	ret := _mock.Called(ctx, bucket, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, bucket, objectKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// S3Client_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type S3Client_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - objectKey string
func (_e *S3Client_Expecter) DeleteObject(ctx interface{}, bucket interface{}, objectKey interface{}) *S3Client_DeleteObject_Call {
	return &S3Client_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, bucket, objectKey)}
}

func (_c *S3Client_DeleteObject_Call) Run(run func(ctx context.Context, bucket string, objectKey string)) *S3Client_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *S3Client_DeleteObject_Call) Return(err error) *S3Client_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *S3Client_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, objectKey string) error) *S3Client_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObjects provides a mock function for the type S3Client
func (_mock *S3Client) DeleteObjects(ctx context.Context, bucketName string, objectKeys []string) (map[string]error, error) {
	ret := _mock.Called(ctx, bucketName, objectKeys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObjects")
	}

	var r0 map[string]error
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (map[string]error, error)); ok {
		return returnFunc(ctx, bucketName, objectKeys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) map[string]error); ok {
		r0 = returnFunc(ctx, bucketName, objectKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]error)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, bucketName, objectKeys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3Client_DeleteObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObjects'
type S3Client_DeleteObjects_Call struct {
	*mock.Call
}

// DeleteObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - objectKeys []string
func (_e *S3Client_Expecter) DeleteObjects(ctx interface{}, bucketName interface{}, objectKeys interface{}) *S3Client_DeleteObjects_Call {
	return &S3Client_DeleteObjects_Call{Call: _e.mock.On("DeleteObjects", ctx, bucketName, objectKeys)}
}

func (_c *S3Client_DeleteObjects_Call) Run(run func(ctx context.Context, bucketName string, objectKeys []string)) *S3Client_DeleteObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *S3Client_DeleteObjects_Call) Return(stringToErr map[string]error, err error) *S3Client_DeleteObjects_Call {
	_c.Call.Return(stringToErr, err)
	return _c
}

func (_c *S3Client_DeleteObjects_Call) RunAndReturn(run func(ctx context.Context, bucketName string, objectKeys []string) (map[string]error, error)) *S3Client_DeleteObjects_Call {
	_c.Call.Return(run)
	return _c
}

// GeneratePresignedGetURL provides a mock function for the type S3Client
func (_mock *S3Client) GeneratePresignedGetURL(ctx context.Context, bucketName string, objectKey string, ttl time.Duration) (*url.URL, error) {
	ret := _mock.Called(ctx, bucketName, objectKey, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignedGetURL")
	}

	var r0 *url.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (*url.URL, error)); ok {
		return returnFunc(ctx, bucketName, objectKey, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) *url.URL); ok {
		r0 = returnFunc(ctx, bucketName, objectKey, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, bucketName, objectKey, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3Client_GeneratePresignedGetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePresignedGetURL'
type S3Client_GeneratePresignedGetURL_Call struct {
	*mock.Call
}

// GeneratePresignedGetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - objectKey string
//   - ttl time.Duration
func (_e *S3Client_Expecter) GeneratePresignedGetURL(ctx interface{}, bucketName interface{}, objectKey interface{}, ttl interface{}) *S3Client_GeneratePresignedGetURL_Call {
	return &S3Client_GeneratePresignedGetURL_Call{Call: _e.mock.On("GeneratePresignedGetURL", ctx, bucketName, objectKey, ttl)}
}

func (_c *S3Client_GeneratePresignedGetURL_Call) Run(run func(ctx context.Context, bucketName string, objectKey string, ttl time.Duration)) *S3Client_GeneratePresignedGetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *S3Client_GeneratePresignedGetURL_Call) Return(uRL *url.URL, err error) *S3Client_GeneratePresignedGetURL_Call {
	_c.Call.Return(uRL, err)
	return _c
}

func (_c *S3Client_GeneratePresignedGetURL_Call) RunAndReturn(run func(ctx context.Context, bucketName string, objectKey string, ttl time.Duration) (*url.URL, error)) *S3Client_GeneratePresignedGetURL_Call {
	_c.Call.Return(run)
	return _c
}

// GeneratePresignedPutURL provides a mock function for the type S3Client
func (_mock *S3Client) GeneratePresignedPutURL(ctx context.Context, bucketName string, objectKey string, objectSize int64, sha256Sum string, ttl time.Duration) (*url.URL, error) {
	ret := _mock.Called(ctx, bucketName, objectKey, objectSize, sha256Sum, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignedPutURL")
	}

	var r0 *url.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, string, time.Duration) (*url.URL, error)); ok {
		return returnFunc(ctx, bucketName, objectKey, objectSize, sha256Sum, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, string, time.Duration) *url.URL); ok {
		r0 = returnFunc(ctx, bucketName, objectKey, objectSize, sha256Sum, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, bucketName, objectKey, objectSize, sha256Sum, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3Client_GeneratePresignedPutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePresignedPutURL'
type S3Client_GeneratePresignedPutURL_Call struct {
	*mock.Call
}

// GeneratePresignedPutURL is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - objectKey string
//   - objectSize int64
//   - sha256Sum string
//   - ttl time.Duration
func (_e *S3Client_Expecter) GeneratePresignedPutURL(ctx interface{}, bucketName interface{}, objectKey interface{}, objectSize interface{}, sha256Sum interface{}, ttl interface{}) *S3Client_GeneratePresignedPutURL_Call {
	return &S3Client_GeneratePresignedPutURL_Call{Call: _e.mock.On("GeneratePresignedPutURL", ctx, bucketName, objectKey, objectSize, sha256Sum, ttl)}
}

func (_c *S3Client_GeneratePresignedPutURL_Call) Run(run func(ctx context.Context, bucketName string, objectKey string, objectSize int64, sha256Sum string, ttl time.Duration)) *S3Client_GeneratePresignedPutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Duration
		if args[5] != nil {
			arg5 = args[5].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *S3Client_GeneratePresignedPutURL_Call) Return(uRL *url.URL, err error) *S3Client_GeneratePresignedPutURL_Call {
	_c.Call.Return(uRL, err)
	return _c
}

func (_c *S3Client_GeneratePresignedPutURL_Call) RunAndReturn(run func(ctx context.Context, bucketName string, objectKey string, objectSize int64, sha256Sum string, ttl time.Duration) (*url.URL, error)) *S3Client_GeneratePresignedPutURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type S3Client
func (_mock *S3Client) GetObject(ctx context.Context, bucket string, objectKey string) (goutils.S3ObjectStat, goutils.S3ObjectReader, error) {
	ret := _mock.Called(ctx, bucket, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 goutils.S3ObjectStat
	var r1 goutils.S3ObjectReader
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (goutils.S3ObjectStat, goutils.S3ObjectReader, error)); ok {
		return returnFunc(ctx, bucket, objectKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) goutils.S3ObjectStat); ok {
		r0 = returnFunc(ctx, bucket, objectKey)
	} else {
		r0 = ret.Get(0).(goutils.S3ObjectStat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) goutils.S3ObjectReader); ok {
		r1 = returnFunc(ctx, bucket, objectKey)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(goutils.S3ObjectReader)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, bucket, objectKey)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// S3Client_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type S3Client_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - objectKey string
func (_e *S3Client_Expecter) GetObject(ctx interface{}, bucket interface{}, objectKey interface{}) *S3Client_GetObject_Call {
	return &S3Client_GetObject_Call{Call: _e.mock.On("GetObject", ctx, bucket, objectKey)}
}

func (_c *S3Client_GetObject_Call) Run(run func(ctx context.Context, bucket string, objectKey string)) *S3Client_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *S3Client_GetObject_Call) Return(s3ObjectStat goutils.S3ObjectStat, s3ObjectReader goutils.S3ObjectReader, err error) *S3Client_GetObject_Call {
	_c.Call.Return(s3ObjectStat, s3ObjectReader, err)
	return _c
}

func (_c *S3Client_GetObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, objectKey string) (goutils.S3ObjectStat, goutils.S3ObjectReader, error)) *S3Client_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectStat provides a mock function for the type S3Client
func (_mock *S3Client) GetObjectStat(ctx context.Context, bucket string, objectKey string) (goutils.S3ObjectStat, error) {
	ret := _mock.Called(ctx, bucket, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectStat")
	}

	var r0 goutils.S3ObjectStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (goutils.S3ObjectStat, error)); ok {
		return returnFunc(ctx, bucket, objectKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) goutils.S3ObjectStat); ok {
		r0 = returnFunc(ctx, bucket, objectKey)
	} else {
		r0 = ret.Get(0).(goutils.S3ObjectStat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, objectKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3Client_GetObjectStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectStat'
type S3Client_GetObjectStat_Call struct {
	*mock.Call
}

// GetObjectStat is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - objectKey string
func (_e *S3Client_Expecter) GetObjectStat(ctx interface{}, bucket interface{}, objectKey interface{}) *S3Client_GetObjectStat_Call {
	return &S3Client_GetObjectStat_Call{Call: _e.mock.On("GetObjectStat", ctx, bucket, objectKey)}
}

func (_c *S3Client_GetObjectStat_Call) Run(run func(ctx context.Context, bucket string, objectKey string)) *S3Client_GetObjectStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *S3Client_GetObjectStat_Call) Return(s3ObjectStat goutils.S3ObjectStat, err error) *S3Client_GetObjectStat_Call {
	_c.Call.Return(s3ObjectStat, err)
	return _c
}

func (_c *S3Client_GetObjectStat_Call) RunAndReturn(run func(ctx context.Context, bucket string, objectKey string) (goutils.S3ObjectStat, error)) *S3Client_GetObjectStat_Call {
	_c.Call.Return(run)
	return _c
}

// ListBuckets provides a mock function for the type S3Client
func (_mock *S3Client) ListBuckets(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBuckets")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3Client_ListBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBuckets'
type S3Client_ListBuckets_Call struct {
	*mock.Call
}

// ListBuckets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *S3Client_Expecter) ListBuckets(ctx interface{}) *S3Client_ListBuckets_Call {
	return &S3Client_ListBuckets_Call{Call: _e.mock.On("ListBuckets", ctx)}
}

func (_c *S3Client_ListBuckets_Call) Run(run func(ctx context.Context)) *S3Client_ListBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *S3Client_ListBuckets_Call) Return(strings []string, err error) *S3Client_ListBuckets_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *S3Client_ListBuckets_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *S3Client_ListBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjects provides a mock function for the type S3Client
func (_mock *S3Client) ListObjects(ctx context.Context, bucket string, prefix *string, startingKey *string, maxKeys *int) ([]string, error) {
	ret := _mock.Called(ctx, bucket, prefix, startingKey, maxKeys)

	if len(ret) == 0 {
		panic("no return value specified for ListObjects")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, *string, *int) ([]string, error)); ok {
		return returnFunc(ctx, bucket, prefix, startingKey, maxKeys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, *string, *int) []string); ok {
		r0 = returnFunc(ctx, bucket, prefix, startingKey, maxKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, *string, *int) error); ok {
		r1 = returnFunc(ctx, bucket, prefix, startingKey, maxKeys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3Client_ListObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjects'
type S3Client_ListObjects_Call struct {
	*mock.Call
}

// ListObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - prefix *string
//   - startingKey *string
//   - maxKeys *int
func (_e *S3Client_Expecter) ListObjects(ctx interface{}, bucket interface{}, prefix interface{}, startingKey interface{}, maxKeys interface{}) *S3Client_ListObjects_Call {
	return &S3Client_ListObjects_Call{Call: _e.mock.On("ListObjects", ctx, bucket, prefix, startingKey, maxKeys)}
}

func (_c *S3Client_ListObjects_Call) Run(run func(ctx context.Context, bucket string, prefix *string, startingKey *string, maxKeys *int)) *S3Client_ListObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *int
		if args[4] != nil {
			arg4 = args[4].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *S3Client_ListObjects_Call) Return(strings []string, err error) *S3Client_ListObjects_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *S3Client_ListObjects_Call) RunAndReturn(run func(ctx context.Context, bucket string, prefix *string, startingKey *string, maxKeys *int) ([]string, error)) *S3Client_ListObjects_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type S3Client
func (_mock *S3Client) PutObject(ctx context.Context, bucket string, objectKey string, data io.Reader, expectedSize int64, contentType *string) error {
	ret := _mock.Called(ctx, bucket, objectKey, data, expectedSize, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, int64, *string) error); ok {
		r0 = returnFunc(ctx, bucket, objectKey, data, expectedSize, contentType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// S3Client_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type S3Client_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - objectKey string
//   - data io.Reader
//   - expectedSize int64
//   - contentType *string
func (_e *S3Client_Expecter) PutObject(ctx interface{}, bucket interface{}, objectKey interface{}, data interface{}, expectedSize interface{}, contentType interface{}) *S3Client_PutObject_Call {
	return &S3Client_PutObject_Call{Call: _e.mock.On("PutObject", ctx, bucket, objectKey, data, expectedSize, contentType)}
}

func (_c *S3Client_PutObject_Call) Run(run func(ctx context.Context, bucket string, objectKey string, data io.Reader, expectedSize int64, contentType *string)) *S3Client_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *S3Client_PutObject_Call) Return(err error) *S3Client_PutObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *S3Client_PutObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, objectKey string, data io.Reader, expectedSize int64, contentType *string) error) *S3Client_PutObject_Call {
	_c.Call.Return(run)
	return _c
}
