// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	"context"
	"time"

	"github.com/alwitt/goutils"
	mock "github.com/stretchr/testify/mock"
)

// NewS3ClientManager creates a new instance of S3ClientManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3ClientManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3ClientManager {
	mock := &S3ClientManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// S3ClientManager is an autogenerated mock type for the S3ClientManager type
type S3ClientManager struct {
	mock.Mock
}

type S3ClientManager_Expecter struct {
	mock *mock.Mock
}

func (_m *S3ClientManager) EXPECT() *S3ClientManager_Expecter {
	return &S3ClientManager_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function for the type S3ClientManager
func (_mock *S3ClientManager) GetClient(ctxt context.Context, timestamp time.Time) (goutils.S3Client, error) {
	ret := _mock.Called(ctxt, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 goutils.S3Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (goutils.S3Client, error)); ok {
		return returnFunc(ctxt, timestamp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) goutils.S3Client); ok {
		r0 = returnFunc(ctxt, timestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goutils.S3Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctxt, timestamp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ClientManager_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type S3ClientManager_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - ctxt context.Context
//   - timestamp time.Time
func (_e *S3ClientManager_Expecter) GetClient(ctxt interface{}, timestamp interface{}) *S3ClientManager_GetClient_Call {
	return &S3ClientManager_GetClient_Call{Call: _e.mock.On("GetClient", ctxt, timestamp)}
}

func (_c *S3ClientManager_GetClient_Call) Run(run func(ctxt context.Context, timestamp time.Time)) *S3ClientManager_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *S3ClientManager_GetClient_Call) Return(s3Client goutils.S3Client, err error) *S3ClientManager_GetClient_Call {
	_c.Call.Return(s3Client, err)
	return _c
}

func (_c *S3ClientManager_GetClient_Call) RunAndReturn(run func(ctxt context.Context, timestamp time.Time) (goutils.S3Client, error)) *S3ClientManager_GetClient_Call {
	_c.Call.Return(run)
	return _c
}
