// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	mock "github.com/stretchr/testify/mock"
)

// NewS3ObjectReader creates a new instance of S3ObjectReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3ObjectReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3ObjectReader {
	mock := &S3ObjectReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// S3ObjectReader is an autogenerated mock type for the S3ObjectReader type
type S3ObjectReader struct {
	mock.Mock
}

type S3ObjectReader_Expecter struct {
	mock *mock.Mock
}

func (_m *S3ObjectReader) EXPECT() *S3ObjectReader_Expecter {
	return &S3ObjectReader_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type S3ObjectReader
func (_mock *S3ObjectReader) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// S3ObjectReader_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type S3ObjectReader_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *S3ObjectReader_Expecter) Close() *S3ObjectReader_Close_Call {
	return &S3ObjectReader_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *S3ObjectReader_Close_Call) Run(run func()) *S3ObjectReader_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *S3ObjectReader_Close_Call) Return(err error) *S3ObjectReader_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *S3ObjectReader_Close_Call) RunAndReturn(run func() error) *S3ObjectReader_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type S3ObjectReader
func (_mock *S3ObjectReader) Read(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ObjectReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type S3ObjectReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *S3ObjectReader_Expecter) Read(p interface{}) *S3ObjectReader_Read_Call {
	return &S3ObjectReader_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *S3ObjectReader_Read_Call) Run(run func(p []byte)) *S3ObjectReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *S3ObjectReader_Read_Call) Return(n int, err error) *S3ObjectReader_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *S3ObjectReader_Read_Call) RunAndReturn(run func(p []byte) (int, error)) *S3ObjectReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAt provides a mock function for the type S3ObjectReader
func (_mock *S3ObjectReader) ReadAt(p []byte, off int64) (int, error) {
	ret := _mock.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for ReadAt")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return returnFunc(p, off)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = returnFunc(p, off)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = returnFunc(p, off)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ObjectReader_ReadAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAt'
type S3ObjectReader_ReadAt_Call struct {
	*mock.Call
}

// ReadAt is a helper method to define mock.On call
//   - p []byte
//   - off int64
func (_e *S3ObjectReader_Expecter) ReadAt(p interface{}, off interface{}) *S3ObjectReader_ReadAt_Call {
	return &S3ObjectReader_ReadAt_Call{Call: _e.mock.On("ReadAt", p, off)}
}

func (_c *S3ObjectReader_ReadAt_Call) Run(run func(p []byte, off int64)) *S3ObjectReader_ReadAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *S3ObjectReader_ReadAt_Call) Return(n int, err error) *S3ObjectReader_ReadAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *S3ObjectReader_ReadAt_Call) RunAndReturn(run func(p []byte, off int64) (int, error)) *S3ObjectReader_ReadAt_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function for the type S3ObjectReader
func (_mock *S3ObjectReader) Seek(offset int64, whence int) (int64, error) {
	ret := _mock.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return returnFunc(offset, whence)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = returnFunc(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = returnFunc(offset, whence)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ObjectReader_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type S3ObjectReader_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - offset int64
//   - whence int
func (_e *S3ObjectReader_Expecter) Seek(offset interface{}, whence interface{}) *S3ObjectReader_Seek_Call {
	return &S3ObjectReader_Seek_Call{Call: _e.mock.On("Seek", offset, whence)}
}

func (_c *S3ObjectReader_Seek_Call) Run(run func(offset int64, whence int)) *S3ObjectReader_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *S3ObjectReader_Seek_Call) Return(n int64, err error) *S3ObjectReader_Seek_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *S3ObjectReader_Seek_Call) RunAndReturn(run func(offset int64, whence int) (int64, error)) *S3ObjectReader_Seek_Call {
	_c.Call.Return(run)
	return _c
}
