// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	mock "github.com/stretchr/testify/mock"
)

// NewSequencer creates a new instance of Sequencer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSequencer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sequencer {
	mock := &Sequencer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Sequencer is an autogenerated mock type for the Sequencer type
type Sequencer struct {
	mock.Mock
}

type Sequencer_Expecter struct {
	mock *mock.Mock
}

func (_m *Sequencer) EXPECT() *Sequencer_Expecter {
	return &Sequencer_Expecter{mock: &_m.Mock}
}

// NextValue provides a mock function for the type Sequencer
func (_mock *Sequencer) NextValue() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextValue")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// Sequencer_NextValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextValue'
type Sequencer_NextValue_Call struct {
	*mock.Call
}

// NextValue is a helper method to define mock.On call
func (_e *Sequencer_Expecter) NextValue() *Sequencer_NextValue_Call {
	return &Sequencer_NextValue_Call{Call: _e.mock.On("NextValue")}
}

func (_c *Sequencer_NextValue_Call) Run(run func()) *Sequencer_NextValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Sequencer_NextValue_Call) Return(f float64) *Sequencer_NextValue_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *Sequencer_NextValue_Call) RunAndReturn(run func() float64) *Sequencer_NextValue_Call {
	_c.Call.Return(run)
	return _c
}
