// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	mock "github.com/stretchr/testify/mock"
)

// newStackCarrier creates a new instance of stackCarrier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newStackCarrier(t interface {
	mock.TestingT
	Cleanup(func())
}) *stackCarrier {
	mock := &stackCarrier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// stackCarrier is an autogenerated mock type for the stackCarrier type
type stackCarrier struct {
	mock.Mock
}

type stackCarrier_Expecter struct {
	mock *mock.Mock
}

func (_m *stackCarrier) EXPECT() *stackCarrier_Expecter {
	return &stackCarrier_Expecter{mock: &_m.Mock}
}

// callStack provides a mock function for the type stackCarrier
func (_mock *stackCarrier) callStack() []uintptr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for callStack")
	}

	var r0 []uintptr
	if returnFunc, ok := ret.Get(0).(func() []uintptr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uintptr)
		}
	}
	return r0
}

// stackCarrier_callStack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'callStack'
type stackCarrier_callStack_Call struct {
	*mock.Call
}

// callStack is a helper method to define mock.On call
func (_e *stackCarrier_Expecter) callStack() *stackCarrier_callStack_Call {
	return &stackCarrier_callStack_Call{Call: _e.mock.On("callStack")}
}

func (_c *stackCarrier_callStack_Call) Run(run func()) *stackCarrier_callStack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *stackCarrier_callStack_Call) Return(uintptrs []uintptr) *stackCarrier_callStack_Call {
	_c.Call.Return(uintptrs)
	return _c
}

func (_c *stackCarrier_callStack_Call) RunAndReturn(run func() []uintptr) *stackCarrier_callStack_Call {
	_c.Call.Return(run)
	return _c
}
