// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoutils

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTaskProcessorMetricHelper creates a new instance of TaskProcessorMetricHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskProcessorMetricHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskProcessorMetricHelper {
	mock := &TaskProcessorMetricHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TaskProcessorMetricHelper is an autogenerated mock type for the TaskProcessorMetricHelper type
type TaskProcessorMetricHelper struct {
	mock.Mock
}

type TaskProcessorMetricHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskProcessorMetricHelper) EXPECT() *TaskProcessorMetricHelper_Expecter {
	return &TaskProcessorMetricHelper_Expecter{mock: &_m.Mock}
}

// RecordProcessed provides a mock function for the type TaskProcessorMetricHelper
func (_mock *TaskProcessorMetricHelper) RecordProcessed(instance string) {
	_mock.Called(instance)
	return
}

// TaskProcessorMetricHelper_RecordProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordProcessed'
type TaskProcessorMetricHelper_RecordProcessed_Call struct {
	*mock.Call
}

// RecordProcessed is a helper method to define mock.On call
//   - instance string
func (_e *TaskProcessorMetricHelper_Expecter) RecordProcessed(instance interface{}) *TaskProcessorMetricHelper_RecordProcessed_Call {
	return &TaskProcessorMetricHelper_RecordProcessed_Call{Call: _e.mock.On("RecordProcessed", instance)}
}

func (_c *TaskProcessorMetricHelper_RecordProcessed_Call) Run(run func(instance string)) *TaskProcessorMetricHelper_RecordProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskProcessorMetricHelper_RecordProcessed_Call) Return() *TaskProcessorMetricHelper_RecordProcessed_Call {
	_c.Call.Return()
	return _c
}

func (_c *TaskProcessorMetricHelper_RecordProcessed_Call) RunAndReturn(run func(instance string)) *TaskProcessorMetricHelper_RecordProcessed_Call {
	_c.Run(run)
	return _c
}

// RecordSubmit provides a mock function for the type TaskProcessorMetricHelper
func (_mock *TaskProcessorMetricHelper) RecordSubmit(instance string, successful bool) {
	_mock.Called(instance, successful)
	return
}

// TaskProcessorMetricHelper_RecordSubmit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordSubmit'
type TaskProcessorMetricHelper_RecordSubmit_Call struct {
	*mock.Call
}

// RecordSubmit is a helper method to define mock.On call
//   - instance string
//   - successful bool
func (_e *TaskProcessorMetricHelper_Expecter) RecordSubmit(instance interface{}, successful interface{}) *TaskProcessorMetricHelper_RecordSubmit_Call {
	return &TaskProcessorMetricHelper_RecordSubmit_Call{Call: _e.mock.On("RecordSubmit", instance, successful)}
}

func (_c *TaskProcessorMetricHelper_RecordSubmit_Call) Run(run func(instance string, successful bool)) *TaskProcessorMetricHelper_RecordSubmit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TaskProcessorMetricHelper_RecordSubmit_Call) Return() *TaskProcessorMetricHelper_RecordSubmit_Call {
	_c.Call.Return()
	return _c
}

func (_c *TaskProcessorMetricHelper_RecordSubmit_Call) RunAndReturn(run func(instance string, successful bool)) *TaskProcessorMetricHelper_RecordSubmit_Call {
	_c.Run(run)
	return _c
}
