// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockredis

import (
	"context"

	"github.com/alwitt/goutils/redis"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// DeleteQueue provides a mock function for the type Client
func (_mock *Client) DeleteQueue(ctx context.Context, queueName string) error {
	ret := _mock.Called(ctx, queueName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, queueName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_DeleteQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQueue'
type Client_DeleteQueue_Call struct {
	*mock.Call
}

// DeleteQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - queueName string
func (_e *Client_Expecter) DeleteQueue(ctx interface{}, queueName interface{}) *Client_DeleteQueue_Call {
	return &Client_DeleteQueue_Call{Call: _e.mock.On("DeleteQueue", ctx, queueName)}
}

func (_c *Client_DeleteQueue_Call) Run(run func(ctx context.Context, queueName string)) *Client_DeleteQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_DeleteQueue_Call) Return(err error) *Client_DeleteQueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_DeleteQueue_Call) RunAndReturn(run func(ctx context.Context, queueName string) error) *Client_DeleteQueue_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRingBuffer provides a mock function for the type Client
func (_mock *Client) DeleteRingBuffer(ctx context.Context, bufferName string) error {
	ret := _mock.Called(ctx, bufferName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRingBuffer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bufferName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_DeleteRingBuffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRingBuffer'
type Client_DeleteRingBuffer_Call struct {
	*mock.Call
}

// DeleteRingBuffer is a helper method to define mock.On call
//   - ctx context.Context
//   - bufferName string
func (_e *Client_Expecter) DeleteRingBuffer(ctx interface{}, bufferName interface{}) *Client_DeleteRingBuffer_Call {
	return &Client_DeleteRingBuffer_Call{Call: _e.mock.On("DeleteRingBuffer", ctx, bufferName)}
}

func (_c *Client_DeleteRingBuffer_Call) Run(run func(ctx context.Context, bufferName string)) *Client_DeleteRingBuffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_DeleteRingBuffer_Call) Return(err error) *Client_DeleteRingBuffer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_DeleteRingBuffer_Call) RunAndReturn(run func(ctx context.Context, bufferName string) error) *Client_DeleteRingBuffer_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueueHandle provides a mock function for the type Client
func (_mock *Client) GetQueueHandle(ctx context.Context, queueName string) (redis.Queue, error) {
	ret := _mock.Called(ctx, queueName)

	if len(ret) == 0 {
		panic("no return value specified for GetQueueHandle")
	}

	var r0 redis.Queue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (redis.Queue, error)); ok {
		return returnFunc(ctx, queueName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) redis.Queue); ok {
		r0 = returnFunc(ctx, queueName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.Queue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, queueName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetQueueHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueueHandle'
type Client_GetQueueHandle_Call struct {
	*mock.Call
}

// GetQueueHandle is a helper method to define mock.On call
//   - ctx context.Context
//   - queueName string
func (_e *Client_Expecter) GetQueueHandle(ctx interface{}, queueName interface{}) *Client_GetQueueHandle_Call {
	return &Client_GetQueueHandle_Call{Call: _e.mock.On("GetQueueHandle", ctx, queueName)}
}

func (_c *Client_GetQueueHandle_Call) Run(run func(ctx context.Context, queueName string)) *Client_GetQueueHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetQueueHandle_Call) Return(queue redis.Queue, err error) *Client_GetQueueHandle_Call {
	_c.Call.Return(queue, err)
	return _c
}

func (_c *Client_GetQueueHandle_Call) RunAndReturn(run func(ctx context.Context, queueName string) (redis.Queue, error)) *Client_GetQueueHandle_Call {
	_c.Call.Return(run)
	return _c
}

// GetRingBuffer provides a mock function for the type Client
func (_mock *Client) GetRingBuffer(ctx context.Context, bufferName string, capacity int64) (redis.RingBuffer, error) {
	ret := _mock.Called(ctx, bufferName, capacity)

	if len(ret) == 0 {
		panic("no return value specified for GetRingBuffer")
	}

	var r0 redis.RingBuffer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (redis.RingBuffer, error)); ok {
		return returnFunc(ctx, bufferName, capacity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) redis.RingBuffer); ok {
		r0 = returnFunc(ctx, bufferName, capacity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.RingBuffer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, bufferName, capacity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetRingBuffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRingBuffer'
type Client_GetRingBuffer_Call struct {
	*mock.Call
}

// GetRingBuffer is a helper method to define mock.On call
//   - ctx context.Context
//   - bufferName string
//   - capacity int64
func (_e *Client_Expecter) GetRingBuffer(ctx interface{}, bufferName interface{}, capacity interface{}) *Client_GetRingBuffer_Call {
	return &Client_GetRingBuffer_Call{Call: _e.mock.On("GetRingBuffer", ctx, bufferName, capacity)}
}

func (_c *Client_GetRingBuffer_Call) Run(run func(ctx context.Context, bufferName string, capacity int64)) *Client_GetRingBuffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_GetRingBuffer_Call) Return(ringBuffer redis.RingBuffer, err error) *Client_GetRingBuffer_Call {
	_c.Call.Return(ringBuffer, err)
	return _c
}

func (_c *Client_GetRingBuffer_Call) RunAndReturn(run func(ctx context.Context, bufferName string, capacity int64) (redis.RingBuffer, error)) *Client_GetRingBuffer_Call {
	_c.Call.Return(run)
	return _c
}
