// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockredis

import (
	"context"
	"time"

	"github.com/alwitt/goutils/redis"
	mock "github.com/stretchr/testify/mock"
)

// NewQueue creates a new instance of Queue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *Queue {
	mock := &Queue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Queue is an autogenerated mock type for the Queue type
type Queue struct {
	mock.Mock
}

type Queue_Expecter struct {
	mock *mock.Mock
}

func (_m *Queue) EXPECT() *Queue_Expecter {
	return &Queue_Expecter{mock: &_m.Mock}
}

// Length provides a mock function for the type Queue
func (_mock *Queue) Length(ctx context.Context) (uint64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Length")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_Length_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Length'
type Queue_Length_Call struct {
	*mock.Call
}

// Length is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Queue_Expecter) Length(ctx interface{}) *Queue_Length_Call {
	return &Queue_Length_Call{Call: _e.mock.On("Length", ctx)}
}

func (_c *Queue_Length_Call) Run(run func(ctx context.Context)) *Queue_Length_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Queue_Length_Call) Return(v uint64, err error) *Queue_Length_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Queue_Length_Call) RunAndReturn(run func(ctx context.Context) (uint64, error)) *Queue_Length_Call {
	_c.Call.Return(run)
	return _c
}

// PeakLeft provides a mock function for the type Queue
func (_mock *Queue) PeakLeft(ctx context.Context) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PeakLeft")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_PeakLeft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeakLeft'
type Queue_PeakLeft_Call struct {
	*mock.Call
}

// PeakLeft is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Queue_Expecter) PeakLeft(ctx interface{}) *Queue_PeakLeft_Call {
	return &Queue_PeakLeft_Call{Call: _e.mock.On("PeakLeft", ctx)}
}

func (_c *Queue_PeakLeft_Call) Run(run func(ctx context.Context)) *Queue_PeakLeft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Queue_PeakLeft_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *Queue_PeakLeft_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *Queue_PeakLeft_Call) RunAndReturn(run func(ctx context.Context) (redis.QueueMessageEnvelope, error)) *Queue_PeakLeft_Call {
	_c.Call.Return(run)
	return _c
}

// PeakRight provides a mock function for the type Queue
func (_mock *Queue) PeakRight(ctx context.Context) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PeakRight")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_PeakRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeakRight'
type Queue_PeakRight_Call struct {
	*mock.Call
}

// PeakRight is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Queue_Expecter) PeakRight(ctx interface{}) *Queue_PeakRight_Call {
	return &Queue_PeakRight_Call{Call: _e.mock.On("PeakRight", ctx)}
}

func (_c *Queue_PeakRight_Call) Run(run func(ctx context.Context)) *Queue_PeakRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Queue_PeakRight_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *Queue_PeakRight_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *Queue_PeakRight_Call) RunAndReturn(run func(ctx context.Context) (redis.QueueMessageEnvelope, error)) *Queue_PeakRight_Call {
	_c.Call.Return(run)
	return _c
}

// PopLeft provides a mock function for the type Queue
func (_mock *Queue) PopLeft(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx, blocking, maxWait)

	if len(ret) == 0 {
		panic("no return value specified for PopLeft")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx, blocking, maxWait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx, blocking, maxWait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, *time.Duration) error); ok {
		r1 = returnFunc(ctx, blocking, maxWait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_PopLeft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopLeft'
type Queue_PopLeft_Call struct {
	*mock.Call
}

// PopLeft is a helper method to define mock.On call
//   - ctx context.Context
//   - blocking bool
//   - maxWait *time.Duration
func (_e *Queue_Expecter) PopLeft(ctx interface{}, blocking interface{}, maxWait interface{}) *Queue_PopLeft_Call {
	return &Queue_PopLeft_Call{Call: _e.mock.On("PopLeft", ctx, blocking, maxWait)}
}

func (_c *Queue_PopLeft_Call) Run(run func(ctx context.Context, blocking bool, maxWait *time.Duration)) *Queue_PopLeft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Queue_PopLeft_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *Queue_PopLeft_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *Queue_PopLeft_Call) RunAndReturn(run func(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error)) *Queue_PopLeft_Call {
	_c.Call.Return(run)
	return _c
}

// PopLeftAndMove provides a mock function for the type Queue
func (_mock *Queue) PopLeftAndMove(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx, destination, insertOnLeft, blocking, maxWait)

	if len(ret) == 0 {
		panic("no return value specified for PopLeftAndMove")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool, *time.Duration) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool, *time.Duration) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool, bool, *time.Duration) error); ok {
		r1 = returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_PopLeftAndMove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopLeftAndMove'
type Queue_PopLeftAndMove_Call struct {
	*mock.Call
}

// PopLeftAndMove is a helper method to define mock.On call
//   - ctx context.Context
//   - destination string
//   - insertOnLeft bool
//   - blocking bool
//   - maxWait *time.Duration
func (_e *Queue_Expecter) PopLeftAndMove(ctx interface{}, destination interface{}, insertOnLeft interface{}, blocking interface{}, maxWait interface{}) *Queue_PopLeftAndMove_Call {
	return &Queue_PopLeftAndMove_Call{Call: _e.mock.On("PopLeftAndMove", ctx, destination, insertOnLeft, blocking, maxWait)}
}

func (_c *Queue_PopLeftAndMove_Call) Run(run func(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration)) *Queue_PopLeftAndMove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 *time.Duration
		if args[4] != nil {
			arg4 = args[4].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Queue_PopLeftAndMove_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *Queue_PopLeftAndMove_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *Queue_PopLeftAndMove_Call) RunAndReturn(run func(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error)) *Queue_PopLeftAndMove_Call {
	_c.Call.Return(run)
	return _c
}

// PopRight provides a mock function for the type Queue
func (_mock *Queue) PopRight(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx, blocking, maxWait)

	if len(ret) == 0 {
		panic("no return value specified for PopRight")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx, blocking, maxWait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx, blocking, maxWait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, *time.Duration) error); ok {
		r1 = returnFunc(ctx, blocking, maxWait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_PopRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopRight'
type Queue_PopRight_Call struct {
	*mock.Call
}

// PopRight is a helper method to define mock.On call
//   - ctx context.Context
//   - blocking bool
//   - maxWait *time.Duration
func (_e *Queue_Expecter) PopRight(ctx interface{}, blocking interface{}, maxWait interface{}) *Queue_PopRight_Call {
	return &Queue_PopRight_Call{Call: _e.mock.On("PopRight", ctx, blocking, maxWait)}
}

func (_c *Queue_PopRight_Call) Run(run func(ctx context.Context, blocking bool, maxWait *time.Duration)) *Queue_PopRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Queue_PopRight_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *Queue_PopRight_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *Queue_PopRight_Call) RunAndReturn(run func(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error)) *Queue_PopRight_Call {
	_c.Call.Return(run)
	return _c
}

// PopRightAndMove provides a mock function for the type Queue
func (_mock *Queue) PopRightAndMove(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx, destination, insertOnLeft, blocking, maxWait)

	if len(ret) == 0 {
		panic("no return value specified for PopRightAndMove")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool, *time.Duration) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool, *time.Duration) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool, bool, *time.Duration) error); ok {
		r1 = returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_PopRightAndMove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopRightAndMove'
type Queue_PopRightAndMove_Call struct {
	*mock.Call
}

// PopRightAndMove is a helper method to define mock.On call
//   - ctx context.Context
//   - destination string
//   - insertOnLeft bool
//   - blocking bool
//   - maxWait *time.Duration
func (_e *Queue_Expecter) PopRightAndMove(ctx interface{}, destination interface{}, insertOnLeft interface{}, blocking interface{}, maxWait interface{}) *Queue_PopRightAndMove_Call {
	return &Queue_PopRightAndMove_Call{Call: _e.mock.On("PopRightAndMove", ctx, destination, insertOnLeft, blocking, maxWait)}
}

func (_c *Queue_PopRightAndMove_Call) Run(run func(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration)) *Queue_PopRightAndMove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 *time.Duration
		if args[4] != nil {
			arg4 = args[4].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Queue_PopRightAndMove_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *Queue_PopRightAndMove_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *Queue_PopRightAndMove_Call) RunAndReturn(run func(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error)) *Queue_PopRightAndMove_Call {
	_c.Call.Return(run)
	return _c
}

// PushLeft provides a mock function for the type Queue
func (_mock *Queue) PushLeft(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration) (uint64, error) {
	ret := _mock.Called(ctx, message, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PushLeft")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) (uint64, error)); ok {
		return returnFunc(ctx, message, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) uint64); ok {
		r0 = returnFunc(ctx, message, ttl)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) error); ok {
		r1 = returnFunc(ctx, message, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_PushLeft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushLeft'
type Queue_PushLeft_Call struct {
	*mock.Call
}

// PushLeft is a helper method to define mock.On call
//   - ctx context.Context
//   - message redis.QueueMessageEnvelope
//   - ttl *time.Duration
func (_e *Queue_Expecter) PushLeft(ctx interface{}, message interface{}, ttl interface{}) *Queue_PushLeft_Call {
	return &Queue_PushLeft_Call{Call: _e.mock.On("PushLeft", ctx, message, ttl)}
}

func (_c *Queue_PushLeft_Call) Run(run func(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration)) *Queue_PushLeft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.QueueMessageEnvelope
		if args[1] != nil {
			arg1 = args[1].(redis.QueueMessageEnvelope)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Queue_PushLeft_Call) Return(v uint64, err error) *Queue_PushLeft_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Queue_PushLeft_Call) RunAndReturn(run func(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration) (uint64, error)) *Queue_PushLeft_Call {
	_c.Call.Return(run)
	return _c
}

// PushRight provides a mock function for the type Queue
func (_mock *Queue) PushRight(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration) (uint64, error) {
	ret := _mock.Called(ctx, message, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PushRight")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) (uint64, error)); ok {
		return returnFunc(ctx, message, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) uint64); ok {
		r0 = returnFunc(ctx, message, ttl)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) error); ok {
		r1 = returnFunc(ctx, message, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_PushRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushRight'
type Queue_PushRight_Call struct {
	*mock.Call
}

// PushRight is a helper method to define mock.On call
//   - ctx context.Context
//   - message redis.QueueMessageEnvelope
//   - ttl *time.Duration
func (_e *Queue_Expecter) PushRight(ctx interface{}, message interface{}, ttl interface{}) *Queue_PushRight_Call {
	return &Queue_PushRight_Call{Call: _e.mock.On("PushRight", ctx, message, ttl)}
}

func (_c *Queue_PushRight_Call) Run(run func(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration)) *Queue_PushRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.QueueMessageEnvelope
		if args[1] != nil {
			arg1 = args[1].(redis.QueueMessageEnvelope)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Queue_PushRight_Call) Return(v uint64, err error) *Queue_PushRight_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Queue_PushRight_Call) RunAndReturn(run func(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration) (uint64, error)) *Queue_PushRight_Call {
	_c.Call.Return(run)
	return _c
}

// QueueName provides a mock function for the type Queue
func (_mock *Queue) QueueName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for QueueName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Queue_QueueName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueName'
type Queue_QueueName_Call struct {
	*mock.Call
}

// QueueName is a helper method to define mock.On call
func (_e *Queue_Expecter) QueueName() *Queue_QueueName_Call {
	return &Queue_QueueName_Call{Call: _e.mock.On("QueueName")}
}

func (_c *Queue_QueueName_Call) Run(run func()) *Queue_QueueName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Queue_QueueName_Call) Return(s string) *Queue_QueueName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Queue_QueueName_Call) RunAndReturn(run func() string) *Queue_QueueName_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type Queue
func (_mock *Queue) Remove(ctx context.Context, message redis.QueueMessageEnvelope) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queue_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type Queue_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - message redis.QueueMessageEnvelope
func (_e *Queue_Expecter) Remove(ctx interface{}, message interface{}) *Queue_Remove_Call {
	return &Queue_Remove_Call{Call: _e.mock.On("Remove", ctx, message)}
}

func (_c *Queue_Remove_Call) Run(run func(ctx context.Context, message redis.QueueMessageEnvelope)) *Queue_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.QueueMessageEnvelope
		if args[1] != nil {
			arg1 = args[1].(redis.QueueMessageEnvelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queue_Remove_Call) Return(err error) *Queue_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queue_Remove_Call) RunAndReturn(run func(ctx context.Context, message redis.QueueMessageEnvelope) error) *Queue_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAndMove provides a mock function for the type Queue
func (_mock *Queue) RemoveAndMove(ctx context.Context, destination string, message redis.QueueMessageEnvelope, insertOnLeft bool) error {
	ret := _mock.Called(ctx, destination, message, insertOnLeft)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAndMove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, redis.QueueMessageEnvelope, bool) error); ok {
		r0 = returnFunc(ctx, destination, message, insertOnLeft)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queue_RemoveAndMove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAndMove'
type Queue_RemoveAndMove_Call struct {
	*mock.Call
}

// RemoveAndMove is a helper method to define mock.On call
//   - ctx context.Context
//   - destination string
//   - message redis.QueueMessageEnvelope
//   - insertOnLeft bool
func (_e *Queue_Expecter) RemoveAndMove(ctx interface{}, destination interface{}, message interface{}, insertOnLeft interface{}) *Queue_RemoveAndMove_Call {
	return &Queue_RemoveAndMove_Call{Call: _e.mock.On("RemoveAndMove", ctx, destination, message, insertOnLeft)}
}

func (_c *Queue_RemoveAndMove_Call) Run(run func(ctx context.Context, destination string, message redis.QueueMessageEnvelope, insertOnLeft bool)) *Queue_RemoveAndMove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 redis.QueueMessageEnvelope
		if args[2] != nil {
			arg2 = args[2].(redis.QueueMessageEnvelope)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Queue_RemoveAndMove_Call) Return(err error) *Queue_RemoveAndMove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queue_RemoveAndMove_Call) RunAndReturn(run func(ctx context.Context, destination string, message redis.QueueMessageEnvelope, insertOnLeft bool) error) *Queue_RemoveAndMove_Call {
	_c.Call.Return(run)
	return _c
}
