// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockredis

import (
	mock "github.com/stretchr/testify/mock"
)

// NewQueueMessageEnvelope creates a new instance of QueueMessageEnvelope. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueueMessageEnvelope(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueueMessageEnvelope {
	mock := &QueueMessageEnvelope{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QueueMessageEnvelope is an autogenerated mock type for the QueueMessageEnvelope type
type QueueMessageEnvelope struct {
	mock.Mock
}

type QueueMessageEnvelope_Expecter struct {
	mock *mock.Mock
}

func (_m *QueueMessageEnvelope) EXPECT() *QueueMessageEnvelope_Expecter {
	return &QueueMessageEnvelope_Expecter{mock: &_m.Mock}
}

// StringPayload provides a mock function for the type QueueMessageEnvelope
func (_mock *QueueMessageEnvelope) StringPayload() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StringPayload")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueueMessageEnvelope_StringPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StringPayload'
type QueueMessageEnvelope_StringPayload_Call struct {
	*mock.Call
}

// StringPayload is a helper method to define mock.On call
func (_e *QueueMessageEnvelope_Expecter) StringPayload() *QueueMessageEnvelope_StringPayload_Call {
	return &QueueMessageEnvelope_StringPayload_Call{Call: _e.mock.On("StringPayload")}
}

func (_c *QueueMessageEnvelope_StringPayload_Call) Run(run func()) *QueueMessageEnvelope_StringPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueueMessageEnvelope_StringPayload_Call) Return(s string, err error) *QueueMessageEnvelope_StringPayload_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *QueueMessageEnvelope_StringPayload_Call) RunAndReturn(run func() (string, error)) *QueueMessageEnvelope_StringPayload_Call {
	_c.Call.Return(run)
	return _c
}
