// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockredis

import (
	"context"
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewRingBuffer creates a new instance of RingBuffer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRingBuffer(t interface {
	mock.TestingT
	Cleanup(func())
}) *RingBuffer {
	mock := &RingBuffer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RingBuffer is an autogenerated mock type for the RingBuffer type
type RingBuffer struct {
	mock.Mock
}

type RingBuffer_Expecter struct {
	mock *mock.Mock
}

func (_m *RingBuffer) EXPECT() *RingBuffer_Expecter {
	return &RingBuffer_Expecter{mock: &_m.Mock}
}

// AsReadWriteCloser provides a mock function for the type RingBuffer
func (_mock *RingBuffer) AsReadWriteCloser(parentCtx context.Context, initReadOffset int64, dataCheckInt time.Duration) io.ReadWriteCloser {
	ret := _mock.Called(parentCtx, initReadOffset, dataCheckInt)

	if len(ret) == 0 {
		panic("no return value specified for AsReadWriteCloser")
	}

	var r0 io.ReadWriteCloser
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Duration) io.ReadWriteCloser); ok {
		r0 = returnFunc(parentCtx, initReadOffset, dataCheckInt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadWriteCloser)
		}
	}
	return r0
}

// RingBuffer_AsReadWriteCloser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsReadWriteCloser'
type RingBuffer_AsReadWriteCloser_Call struct {
	*mock.Call
}

// AsReadWriteCloser is a helper method to define mock.On call
//   - parentCtx context.Context
//   - initReadOffset int64
//   - dataCheckInt time.Duration
func (_e *RingBuffer_Expecter) AsReadWriteCloser(parentCtx interface{}, initReadOffset interface{}, dataCheckInt interface{}) *RingBuffer_AsReadWriteCloser_Call {
	return &RingBuffer_AsReadWriteCloser_Call{Call: _e.mock.On("AsReadWriteCloser", parentCtx, initReadOffset, dataCheckInt)}
}

func (_c *RingBuffer_AsReadWriteCloser_Call) Run(run func(parentCtx context.Context, initReadOffset int64, dataCheckInt time.Duration)) *RingBuffer_AsReadWriteCloser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RingBuffer_AsReadWriteCloser_Call) Return(readWriteCloser io.ReadWriteCloser) *RingBuffer_AsReadWriteCloser_Call {
	_c.Call.Return(readWriteCloser)
	return _c
}

func (_c *RingBuffer_AsReadWriteCloser_Call) RunAndReturn(run func(parentCtx context.Context, initReadOffset int64, dataCheckInt time.Duration) io.ReadWriteCloser) *RingBuffer_AsReadWriteCloser_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAt provides a mock function for the type RingBuffer
func (_mock *RingBuffer) ReadAt(ctx context.Context, buf []byte, offset int64) (int64, int, int64, error) {
	ret := _mock.Called(ctx, buf, offset)

	if len(ret) == 0 {
		panic("no return value specified for ReadAt")
	}

	var r0 int64
	var r1 int
	var r2 int64
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int64) (int64, int, int64, error)); ok {
		return returnFunc(ctx, buf, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int64) int64); ok {
		r0 = returnFunc(ctx, buf, offset)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, int64) int); ok {
		r1 = returnFunc(ctx, buf, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []byte, int64) int64); ok {
		r2 = returnFunc(ctx, buf, offset)
	} else {
		r2 = ret.Get(2).(int64)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, []byte, int64) error); ok {
		r3 = returnFunc(ctx, buf, offset)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// RingBuffer_ReadAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAt'
type RingBuffer_ReadAt_Call struct {
	*mock.Call
}

// ReadAt is a helper method to define mock.On call
//   - ctx context.Context
//   - buf []byte
//   - offset int64
func (_e *RingBuffer_Expecter) ReadAt(ctx interface{}, buf interface{}, offset interface{}) *RingBuffer_ReadAt_Call {
	return &RingBuffer_ReadAt_Call{Call: _e.mock.On("ReadAt", ctx, buf, offset)}
}

func (_c *RingBuffer_ReadAt_Call) Run(run func(ctx context.Context, buf []byte, offset int64)) *RingBuffer_ReadAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RingBuffer_ReadAt_Call) Return(n int64, n1 int, n2 int64, err error) *RingBuffer_ReadAt_Call {
	_c.Call.Return(n, n1, n2, err)
	return _c
}

func (_c *RingBuffer_ReadAt_Call) RunAndReturn(run func(ctx context.Context, buf []byte, offset int64) (int64, int, int64, error)) *RingBuffer_ReadAt_Call {
	_c.Call.Return(run)
	return _c
}

// ReadNewest provides a mock function for the type RingBuffer
func (_mock *RingBuffer) ReadNewest(ctx context.Context, buf []byte) (int64, int, int64, error) {
	ret := _mock.Called(ctx, buf)

	if len(ret) == 0 {
		panic("no return value specified for ReadNewest")
	}

	var r0 int64
	var r1 int
	var r2 int64
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (int64, int, int64, error)); ok {
		return returnFunc(ctx, buf)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) int64); ok {
		r0 = returnFunc(ctx, buf)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) int); ok {
		r1 = returnFunc(ctx, buf)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []byte) int64); ok {
		r2 = returnFunc(ctx, buf)
	} else {
		r2 = ret.Get(2).(int64)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, []byte) error); ok {
		r3 = returnFunc(ctx, buf)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// RingBuffer_ReadNewest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadNewest'
type RingBuffer_ReadNewest_Call struct {
	*mock.Call
}

// ReadNewest is a helper method to define mock.On call
//   - ctx context.Context
//   - buf []byte
func (_e *RingBuffer_Expecter) ReadNewest(ctx interface{}, buf interface{}) *RingBuffer_ReadNewest_Call {
	return &RingBuffer_ReadNewest_Call{Call: _e.mock.On("ReadNewest", ctx, buf)}
}

func (_c *RingBuffer_ReadNewest_Call) Run(run func(ctx context.Context, buf []byte)) *RingBuffer_ReadNewest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RingBuffer_ReadNewest_Call) Return(n int64, n1 int, n2 int64, err error) *RingBuffer_ReadNewest_Call {
	_c.Call.Return(n, n1, n2, err)
	return _c
}

func (_c *RingBuffer_ReadNewest_Call) RunAndReturn(run func(ctx context.Context, buf []byte) (int64, int, int64, error)) *RingBuffer_ReadNewest_Call {
	_c.Call.Return(run)
	return _c
}

// Total provides a mock function for the type RingBuffer
func (_mock *RingBuffer) Total(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Total")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RingBuffer_Total_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Total'
type RingBuffer_Total_Call struct {
	*mock.Call
}

// Total is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RingBuffer_Expecter) Total(ctx interface{}) *RingBuffer_Total_Call {
	return &RingBuffer_Total_Call{Call: _e.mock.On("Total", ctx)}
}

func (_c *RingBuffer_Total_Call) Run(run func(ctx context.Context)) *RingBuffer_Total_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RingBuffer_Total_Call) Return(n int64, err error) *RingBuffer_Total_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *RingBuffer_Total_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *RingBuffer_Total_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type RingBuffer
func (_mock *RingBuffer) Write(ctx context.Context, data []byte) (int64, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (int64, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) int64); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RingBuffer_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type RingBuffer_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *RingBuffer_Expecter) Write(ctx interface{}, data interface{}) *RingBuffer_Write_Call {
	return &RingBuffer_Write_Call{Call: _e.mock.On("Write", ctx, data)}
}

func (_c *RingBuffer_Write_Call) Run(run func(ctx context.Context, data []byte)) *RingBuffer_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RingBuffer_Write_Call) Return(n int64, err error) *RingBuffer_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *RingBuffer_Write_Call) RunAndReturn(run func(ctx context.Context, data []byte) (int64, error)) *RingBuffer_Write_Call {
	_c.Call.Return(run)
	return _c
}
