// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockredis

import (
	"context"

	"github.com/alwitt/goutils/redis"
	mock "github.com/stretchr/testify/mock"
)

// NewSubscriber creates a new instance of Subscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Subscriber {
	mock := &Subscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

type Subscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *Subscriber) EXPECT() *Subscriber_Expecter {
	return &Subscriber_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type Subscriber
func (_mock *Subscriber) Start(parentCtx context.Context, handler redis.PubSubMessageHandler) error {
	ret := _mock.Called(parentCtx, handler)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.PubSubMessageHandler) error); ok {
		r0 = returnFunc(parentCtx, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Subscriber_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Subscriber_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - parentCtx context.Context
//   - handler redis.PubSubMessageHandler
func (_e *Subscriber_Expecter) Start(parentCtx interface{}, handler interface{}) *Subscriber_Start_Call {
	return &Subscriber_Start_Call{Call: _e.mock.On("Start", parentCtx, handler)}
}

func (_c *Subscriber_Start_Call) Run(run func(parentCtx context.Context, handler redis.PubSubMessageHandler)) *Subscriber_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.PubSubMessageHandler
		if args[1] != nil {
			arg1 = args[1].(redis.PubSubMessageHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Subscriber_Start_Call) Return(err error) *Subscriber_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Subscriber_Start_Call) RunAndReturn(run func(parentCtx context.Context, handler redis.PubSubMessageHandler) error) *Subscriber_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Subscriber
func (_mock *Subscriber) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Subscriber_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Subscriber_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Subscriber_Expecter) Stop(ctx interface{}) *Subscriber_Stop_Call {
	return &Subscriber_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *Subscriber_Stop_Call) Run(run func(ctx context.Context)) *Subscriber_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Subscriber_Stop_Call) Return(err error) *Subscriber_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Subscriber_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *Subscriber_Stop_Call {
	_c.Call.Return(run)
	return _c
}
