// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockruntime

import (
	"context"
	"io"

	"github.com/alwitt/goutils/runtime"
	mock "github.com/stretchr/testify/mock"
)

// NewSystemCallRuntime creates a new instance of SystemCallRuntime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSystemCallRuntime(t interface {
	mock.TestingT
	Cleanup(func())
}) *SystemCallRuntime {
	mock := &SystemCallRuntime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SystemCallRuntime is an autogenerated mock type for the SystemCallRuntime type
type SystemCallRuntime struct {
	mock.Mock
}

type SystemCallRuntime_Expecter struct {
	mock *mock.Mock
}

func (_m *SystemCallRuntime) EXPECT() *SystemCallRuntime_Expecter {
	return &SystemCallRuntime_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type SystemCallRuntime
func (_mock *SystemCallRuntime) Cleanup(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SystemCallRuntime_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type SystemCallRuntime_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SystemCallRuntime_Expecter) Cleanup(ctx interface{}) *SystemCallRuntime_Cleanup_Call {
	return &SystemCallRuntime_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx)}
}

func (_c *SystemCallRuntime_Cleanup_Call) Run(run func(ctx context.Context)) *SystemCallRuntime_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SystemCallRuntime_Cleanup_Call) Return(err error) *SystemCallRuntime_Cleanup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SystemCallRuntime_Cleanup_Call) RunAndReturn(run func(ctx context.Context) error) *SystemCallRuntime_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// PipeInput provides a mock function for the type SystemCallRuntime
func (_mock *SystemCallRuntime) PipeInput(input io.Reader) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for PipeInput")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SystemCallRuntime_PipeInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PipeInput'
type SystemCallRuntime_PipeInput_Call struct {
	*mock.Call
}

// PipeInput is a helper method to define mock.On call
//   - input io.Reader
func (_e *SystemCallRuntime_Expecter) PipeInput(input interface{}) *SystemCallRuntime_PipeInput_Call {
	return &SystemCallRuntime_PipeInput_Call{Call: _e.mock.On("PipeInput", input)}
}

func (_c *SystemCallRuntime_PipeInput_Call) Run(run func(input io.Reader)) *SystemCallRuntime_PipeInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SystemCallRuntime_PipeInput_Call) Return(err error) *SystemCallRuntime_PipeInput_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SystemCallRuntime_PipeInput_Call) RunAndReturn(run func(input io.Reader) error) *SystemCallRuntime_PipeInput_Call {
	_c.Call.Return(run)
	return _c
}

// PipeOutput provides a mock function for the type SystemCallRuntime
func (_mock *SystemCallRuntime) PipeOutput(output io.Writer) error {
	ret := _mock.Called(output)

	if len(ret) == 0 {
		panic("no return value specified for PipeOutput")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer) error); ok {
		r0 = returnFunc(output)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SystemCallRuntime_PipeOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PipeOutput'
type SystemCallRuntime_PipeOutput_Call struct {
	*mock.Call
}

// PipeOutput is a helper method to define mock.On call
//   - output io.Writer
func (_e *SystemCallRuntime_Expecter) PipeOutput(output interface{}) *SystemCallRuntime_PipeOutput_Call {
	return &SystemCallRuntime_PipeOutput_Call{Call: _e.mock.On("PipeOutput", output)}
}

func (_c *SystemCallRuntime_PipeOutput_Call) Run(run func(output io.Writer)) *SystemCallRuntime_PipeOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SystemCallRuntime_PipeOutput_Call) Return(err error) *SystemCallRuntime_PipeOutput_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SystemCallRuntime_PipeOutput_Call) RunAndReturn(run func(output io.Writer) error) *SystemCallRuntime_PipeOutput_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type SystemCallRuntime
func (_mock *SystemCallRuntime) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SystemCallRuntime_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type SystemCallRuntime_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SystemCallRuntime_Expecter) Start(ctx interface{}) *SystemCallRuntime_Start_Call {
	return &SystemCallRuntime_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *SystemCallRuntime_Start_Call) Run(run func(ctx context.Context)) *SystemCallRuntime_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SystemCallRuntime_Start_Call) Return(err error) *SystemCallRuntime_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SystemCallRuntime_Start_Call) RunAndReturn(run func(ctx context.Context) error) *SystemCallRuntime_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type SystemCallRuntime
func (_mock *SystemCallRuntime) Wait(ctx context.Context) (runtime.SystemCallResp, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 runtime.SystemCallResp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (runtime.SystemCallResp, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) runtime.SystemCallResp); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(runtime.SystemCallResp)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SystemCallRuntime_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type SystemCallRuntime_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SystemCallRuntime_Expecter) Wait(ctx interface{}) *SystemCallRuntime_Wait_Call {
	return &SystemCallRuntime_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *SystemCallRuntime_Wait_Call) Run(run func(ctx context.Context)) *SystemCallRuntime_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SystemCallRuntime_Wait_Call) Return(systemCallResp runtime.SystemCallResp, err error) *SystemCallRuntime_Wait_Call {
	_c.Call.Return(systemCallResp, err)
	return _c
}

func (_c *SystemCallRuntime_Wait_Call) RunAndReturn(run func(ctx context.Context) (runtime.SystemCallResp, error)) *SystemCallRuntime_Wait_Call {
	_c.Call.Return(run)
	return _c
}
