// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockruntime

import (
	"context"

	"github.com/alwitt/goutils/runtime"
	mock "github.com/stretchr/testify/mock"
)

// NewVolumeManager creates a new instance of VolumeManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVolumeManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *VolumeManager {
	mock := &VolumeManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VolumeManager is an autogenerated mock type for the VolumeManager type
type VolumeManager struct {
	mock.Mock
}

type VolumeManager_Expecter struct {
	mock *mock.Mock
}

func (_m *VolumeManager) EXPECT() *VolumeManager_Expecter {
	return &VolumeManager_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type VolumeManager
func (_mock *VolumeManager) Cleanup(ctxt context.Context) error {
	ret := _mock.Called(ctxt)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctxt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VolumeManager_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type VolumeManager_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctxt context.Context
func (_e *VolumeManager_Expecter) Cleanup(ctxt interface{}) *VolumeManager_Cleanup_Call {
	return &VolumeManager_Cleanup_Call{Call: _e.mock.On("Cleanup", ctxt)}
}

func (_c *VolumeManager_Cleanup_Call) Run(run func(ctxt context.Context)) *VolumeManager_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VolumeManager_Cleanup_Call) Return(err error) *VolumeManager_Cleanup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VolumeManager_Cleanup_Call) RunAndReturn(run func(ctxt context.Context) error) *VolumeManager_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// DefineVolume provides a mock function for the type VolumeManager
func (_mock *VolumeManager) DefineVolume(ctxt context.Context, volume runtime.ContainerVolume, metadata any) (runtime.ContainerVolume, error) {
	ret := _mock.Called(ctxt, volume, metadata)

	if len(ret) == 0 {
		panic("no return value specified for DefineVolume")
	}

	var r0 runtime.ContainerVolume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtime.ContainerVolume, any) (runtime.ContainerVolume, error)); ok {
		return returnFunc(ctxt, volume, metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtime.ContainerVolume, any) runtime.ContainerVolume); ok {
		r0 = returnFunc(ctxt, volume, metadata)
	} else {
		r0 = ret.Get(0).(runtime.ContainerVolume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, runtime.ContainerVolume, any) error); ok {
		r1 = returnFunc(ctxt, volume, metadata)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VolumeManager_DefineVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineVolume'
type VolumeManager_DefineVolume_Call struct {
	*mock.Call
}

// DefineVolume is a helper method to define mock.On call
//   - ctxt context.Context
//   - volume runtime.ContainerVolume
//   - metadata any
func (_e *VolumeManager_Expecter) DefineVolume(ctxt interface{}, volume interface{}, metadata interface{}) *VolumeManager_DefineVolume_Call {
	return &VolumeManager_DefineVolume_Call{Call: _e.mock.On("DefineVolume", ctxt, volume, metadata)}
}

func (_c *VolumeManager_DefineVolume_Call) Run(run func(ctxt context.Context, volume runtime.ContainerVolume, metadata any)) *VolumeManager_DefineVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runtime.ContainerVolume
		if args[1] != nil {
			arg1 = args[1].(runtime.ContainerVolume)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VolumeManager_DefineVolume_Call) Return(containerVolume runtime.ContainerVolume, err error) *VolumeManager_DefineVolume_Call {
	_c.Call.Return(containerVolume, err)
	return _c
}

func (_c *VolumeManager_DefineVolume_Call) RunAndReturn(run func(ctxt context.Context, volume runtime.ContainerVolume, metadata any) (runtime.ContainerVolume, error)) *VolumeManager_DefineVolume_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVolume provides a mock function for the type VolumeManager
func (_mock *VolumeManager) DeleteVolume(ctxt context.Context, name string, force bool) error {
	ret := _mock.Called(ctxt, name, force)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctxt, name, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VolumeManager_DeleteVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVolume'
type VolumeManager_DeleteVolume_Call struct {
	*mock.Call
}

// DeleteVolume is a helper method to define mock.On call
//   - ctxt context.Context
//   - name string
//   - force bool
func (_e *VolumeManager_Expecter) DeleteVolume(ctxt interface{}, name interface{}, force interface{}) *VolumeManager_DeleteVolume_Call {
	return &VolumeManager_DeleteVolume_Call{Call: _e.mock.On("DeleteVolume", ctxt, name, force)}
}

func (_c *VolumeManager_DeleteVolume_Call) Run(run func(ctxt context.Context, name string, force bool)) *VolumeManager_DeleteVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VolumeManager_DeleteVolume_Call) Return(err error) *VolumeManager_DeleteVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VolumeManager_DeleteVolume_Call) RunAndReturn(run func(ctxt context.Context, name string, force bool) error) *VolumeManager_DeleteVolume_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolume provides a mock function for the type VolumeManager
func (_mock *VolumeManager) GetVolume(ctxt context.Context, name string) (runtime.ContainerVolume, []string, error) {
	ret := _mock.Called(ctxt, name)

	if len(ret) == 0 {
		panic("no return value specified for GetVolume")
	}

	var r0 runtime.ContainerVolume
	var r1 []string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (runtime.ContainerVolume, []string, error)); ok {
		return returnFunc(ctxt, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) runtime.ContainerVolume); ok {
		r0 = returnFunc(ctxt, name)
	} else {
		r0 = ret.Get(0).(runtime.ContainerVolume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) []string); ok {
		r1 = returnFunc(ctxt, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctxt, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// VolumeManager_GetVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolume'
type VolumeManager_GetVolume_Call struct {
	*mock.Call
}

// GetVolume is a helper method to define mock.On call
//   - ctxt context.Context
//   - name string
func (_e *VolumeManager_Expecter) GetVolume(ctxt interface{}, name interface{}) *VolumeManager_GetVolume_Call {
	return &VolumeManager_GetVolume_Call{Call: _e.mock.On("GetVolume", ctxt, name)}
}

func (_c *VolumeManager_GetVolume_Call) Run(run func(ctxt context.Context, name string)) *VolumeManager_GetVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VolumeManager_GetVolume_Call) Return(containerVolume runtime.ContainerVolume, strings []string, err error) *VolumeManager_GetVolume_Call {
	_c.Call.Return(containerVolume, strings, err)
	return _c
}

func (_c *VolumeManager_GetVolume_Call) RunAndReturn(run func(ctxt context.Context, name string) (runtime.ContainerVolume, []string, error)) *VolumeManager_GetVolume_Call {
	_c.Call.Return(run)
	return _c
}

// ListVolumes provides a mock function for the type VolumeManager
func (_mock *VolumeManager) ListVolumes(ctxt context.Context, namePrefix *string) ([]runtime.ContainerVolume, error) {
	ret := _mock.Called(ctxt, namePrefix)

	if len(ret) == 0 {
		panic("no return value specified for ListVolumes")
	}

	var r0 []runtime.ContainerVolume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) ([]runtime.ContainerVolume, error)); ok {
		return returnFunc(ctxt, namePrefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) []runtime.ContainerVolume); ok {
		r0 = returnFunc(ctxt, namePrefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]runtime.ContainerVolume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = returnFunc(ctxt, namePrefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VolumeManager_ListVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVolumes'
type VolumeManager_ListVolumes_Call struct {
	*mock.Call
}

// ListVolumes is a helper method to define mock.On call
//   - ctxt context.Context
//   - namePrefix *string
func (_e *VolumeManager_Expecter) ListVolumes(ctxt interface{}, namePrefix interface{}) *VolumeManager_ListVolumes_Call {
	return &VolumeManager_ListVolumes_Call{Call: _e.mock.On("ListVolumes", ctxt, namePrefix)}
}

func (_c *VolumeManager_ListVolumes_Call) Run(run func(ctxt context.Context, namePrefix *string)) *VolumeManager_ListVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VolumeManager_ListVolumes_Call) Return(containerVolumes []runtime.ContainerVolume, err error) *VolumeManager_ListVolumes_Call {
	_c.Call.Return(containerVolumes, err)
	return _c
}

func (_c *VolumeManager_ListVolumes_Call) RunAndReturn(run func(ctxt context.Context, namePrefix *string) ([]runtime.ContainerVolume, error)) *VolumeManager_ListVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type VolumeManager
func (_mock *VolumeManager) Start(ctxt context.Context) error {
	ret := _mock.Called(ctxt)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctxt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VolumeManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type VolumeManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctxt context.Context
func (_e *VolumeManager_Expecter) Start(ctxt interface{}) *VolumeManager_Start_Call {
	return &VolumeManager_Start_Call{Call: _e.mock.On("Start", ctxt)}
}

func (_c *VolumeManager_Start_Call) Run(run func(ctxt context.Context)) *VolumeManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VolumeManager_Start_Call) Return(err error) *VolumeManager_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VolumeManager_Start_Call) RunAndReturn(run func(ctxt context.Context) error) *VolumeManager_Start_Call {
	_c.Call.Return(run)
	return _c
}
