// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktest

import (
	"context"

	"github.com/alwitt/goutils/redis"
	mock "github.com/stretchr/testify/mock"
)

// NewUnitTestCallbackCollector creates a new instance of UnitTestCallbackCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitTestCallbackCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitTestCallbackCollector {
	mock := &UnitTestCallbackCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnitTestCallbackCollector is an autogenerated mock type for the UnitTestCallbackCollector type
type UnitTestCallbackCollector struct {
	mock.Mock
}

type UnitTestCallbackCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *UnitTestCallbackCollector) EXPECT() *UnitTestCallbackCollector_Expecter {
	return &UnitTestCallbackCollector_Expecter{mock: &_m.Mock}
}

// CollectRedisSubscribeMsgs provides a mock function for the type UnitTestCallbackCollector
func (_mock *UnitTestCallbackCollector) CollectRedisSubscribeMsgs(ctx context.Context, msg redis.PubSubMessage) {
	_mock.Called(ctx, msg)
	return
}

// UnitTestCallbackCollector_CollectRedisSubscribeMsgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectRedisSubscribeMsgs'
type UnitTestCallbackCollector_CollectRedisSubscribeMsgs_Call struct {
	*mock.Call
}

// CollectRedisSubscribeMsgs is a helper method to define mock.On call
//   - ctx context.Context
//   - msg redis.PubSubMessage
func (_e *UnitTestCallbackCollector_Expecter) CollectRedisSubscribeMsgs(ctx interface{}, msg interface{}) *UnitTestCallbackCollector_CollectRedisSubscribeMsgs_Call {
	return &UnitTestCallbackCollector_CollectRedisSubscribeMsgs_Call{Call: _e.mock.On("CollectRedisSubscribeMsgs", ctx, msg)}
}

func (_c *UnitTestCallbackCollector_CollectRedisSubscribeMsgs_Call) Run(run func(ctx context.Context, msg redis.PubSubMessage)) *UnitTestCallbackCollector_CollectRedisSubscribeMsgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.PubSubMessage
		if args[1] != nil {
			arg1 = args[1].(redis.PubSubMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UnitTestCallbackCollector_CollectRedisSubscribeMsgs_Call) Return() *UnitTestCallbackCollector_CollectRedisSubscribeMsgs_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnitTestCallbackCollector_CollectRedisSubscribeMsgs_Call) RunAndReturn(run func(ctx context.Context, msg redis.PubSubMessage)) *UnitTestCallbackCollector_CollectRedisSubscribeMsgs_Call {
	_c.Run(run)
	return _c
}
